// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"io"
	"iter"

	"github.com/gofrs/uuid/v5"
	"github.com/opencontainers/go-digest"
	"github.com/robinkb/cascade/registry/store"
	mock "github.com/stretchr/testify/mock"
)

// NewBlobs creates a new instance of Blobs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlobs(t interface {
	mock.TestingT
	Cleanup(func())
}) *Blobs {
	mock := &Blobs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Blobs is an autogenerated mock type for the Blobs type
type Blobs struct {
	mock.Mock
}

type Blobs_Expecter struct {
	mock *mock.Mock
}

func (_m *Blobs) EXPECT() *Blobs_Expecter {
	return &Blobs_Expecter{mock: &_m.Mock}
}

// AllBlobs provides a mock function for the type Blobs
func (_mock *Blobs) AllBlobs() iter.Seq2[digest.Digest, error] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllBlobs")
	}

	var r0 iter.Seq2[digest.Digest, error]
	if returnFunc, ok := ret.Get(0).(func() iter.Seq2[digest.Digest, error]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[digest.Digest, error])
		}
	}
	return r0
}

// Blobs_AllBlobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllBlobs'
type Blobs_AllBlobs_Call struct {
	*mock.Call
}

// AllBlobs is a helper method to define mock.On call
func (_e *Blobs_Expecter) AllBlobs() *Blobs_AllBlobs_Call {
	return &Blobs_AllBlobs_Call{Call: _e.mock.On("AllBlobs")}
}

func (_c *Blobs_AllBlobs_Call) Run(run func()) *Blobs_AllBlobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Blobs_AllBlobs_Call) Return(seq2 iter.Seq2[digest.Digest, error]) *Blobs_AllBlobs_Call {
	_c.Call.Return(seq2)
	return _c
}

func (_c *Blobs_AllBlobs_Call) RunAndReturn(run func() iter.Seq2[digest.Digest, error]) *Blobs_AllBlobs_Call {
	_c.Call.Return(run)
	return _c
}

// BlobReader provides a mock function for the type Blobs
func (_mock *Blobs) BlobReader(id digest.Digest) (io.Reader, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for BlobReader")
	}

	var r0 io.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) (io.Reader, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) io.Reader); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(digest.Digest) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Blobs_BlobReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlobReader'
type Blobs_BlobReader_Call struct {
	*mock.Call
}

// BlobReader is a helper method to define mock.On call
//   - id digest.Digest
func (_e *Blobs_Expecter) BlobReader(id interface{}) *Blobs_BlobReader_Call {
	return &Blobs_BlobReader_Call{Call: _e.mock.On("BlobReader", id)}
}

func (_c *Blobs_BlobReader_Call) Run(run func(id digest.Digest)) *Blobs_BlobReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Blobs_BlobReader_Call) Return(reader io.Reader, err error) *Blobs_BlobReader_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *Blobs_BlobReader_Call) RunAndReturn(run func(id digest.Digest) (io.Reader, error)) *Blobs_BlobReader_Call {
	_c.Call.Return(run)
	return _c
}

// BlobWriter provides a mock function for the type Blobs
func (_mock *Blobs) BlobWriter(id digest.Digest) (io.Writer, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for BlobWriter")
	}

	var r0 io.Writer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) (io.Writer, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) io.Writer); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(digest.Digest) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Blobs_BlobWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlobWriter'
type Blobs_BlobWriter_Call struct {
	*mock.Call
}

// BlobWriter is a helper method to define mock.On call
//   - id digest.Digest
func (_e *Blobs_Expecter) BlobWriter(id interface{}) *Blobs_BlobWriter_Call {
	return &Blobs_BlobWriter_Call{Call: _e.mock.On("BlobWriter", id)}
}

func (_c *Blobs_BlobWriter_Call) Run(run func(id digest.Digest)) *Blobs_BlobWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Blobs_BlobWriter_Call) Return(writer io.Writer, err error) *Blobs_BlobWriter_Call {
	_c.Call.Return(writer, err)
	return _c
}

func (_c *Blobs_BlobWriter_Call) RunAndReturn(run func(id digest.Digest) (io.Writer, error)) *Blobs_BlobWriter_Call {
	_c.Call.Return(run)
	return _c
}

// CloseUpload provides a mock function for the type Blobs
func (_mock *Blobs) CloseUpload(id uuid.UUID, digest1 digest.Digest) error {
	ret := _mock.Called(id, digest1)

	if len(ret) == 0 {
		panic("no return value specified for CloseUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, digest.Digest) error); ok {
		r0 = returnFunc(id, digest1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Blobs_CloseUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseUpload'
type Blobs_CloseUpload_Call struct {
	*mock.Call
}

// CloseUpload is a helper method to define mock.On call
//   - id uuid.UUID
//   - digest1 digest.Digest
func (_e *Blobs_Expecter) CloseUpload(id interface{}, digest1 interface{}) *Blobs_CloseUpload_Call {
	return &Blobs_CloseUpload_Call{Call: _e.mock.On("CloseUpload", id, digest1)}
}

func (_c *Blobs_CloseUpload_Call) Run(run func(id uuid.UUID, digest1 digest.Digest)) *Blobs_CloseUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 digest.Digest
		if args[1] != nil {
			arg1 = args[1].(digest.Digest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Blobs_CloseUpload_Call) Return(err error) *Blobs_CloseUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Blobs_CloseUpload_Call) RunAndReturn(run func(id uuid.UUID, digest1 digest.Digest) error) *Blobs_CloseUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlob provides a mock function for the type Blobs
func (_mock *Blobs) DeleteBlob(id digest.Digest) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Blobs_DeleteBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlob'
type Blobs_DeleteBlob_Call struct {
	*mock.Call
}

// DeleteBlob is a helper method to define mock.On call
//   - id digest.Digest
func (_e *Blobs_Expecter) DeleteBlob(id interface{}) *Blobs_DeleteBlob_Call {
	return &Blobs_DeleteBlob_Call{Call: _e.mock.On("DeleteBlob", id)}
}

func (_c *Blobs_DeleteBlob_Call) Run(run func(id digest.Digest)) *Blobs_DeleteBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Blobs_DeleteBlob_Call) Return(err error) *Blobs_DeleteBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Blobs_DeleteBlob_Call) RunAndReturn(run func(id digest.Digest) error) *Blobs_DeleteBlob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUpload provides a mock function for the type Blobs
func (_mock *Blobs) DeleteUpload(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Blobs_DeleteUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUpload'
type Blobs_DeleteUpload_Call struct {
	*mock.Call
}

// DeleteUpload is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Blobs_Expecter) DeleteUpload(id interface{}) *Blobs_DeleteUpload_Call {
	return &Blobs_DeleteUpload_Call{Call: _e.mock.On("DeleteUpload", id)}
}

func (_c *Blobs_DeleteUpload_Call) Run(run func(id uuid.UUID)) *Blobs_DeleteUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Blobs_DeleteUpload_Call) Return(err error) *Blobs_DeleteUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Blobs_DeleteUpload_Call) RunAndReturn(run func(id uuid.UUID) error) *Blobs_DeleteUpload_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlob provides a mock function for the type Blobs
func (_mock *Blobs) GetBlob(id digest.Digest) ([]byte, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) ([]byte, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) []byte); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(digest.Digest) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Blobs_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type Blobs_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - id digest.Digest
func (_e *Blobs_Expecter) GetBlob(id interface{}) *Blobs_GetBlob_Call {
	return &Blobs_GetBlob_Call{Call: _e.mock.On("GetBlob", id)}
}

func (_c *Blobs_GetBlob_Call) Run(run func(id digest.Digest)) *Blobs_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Blobs_GetBlob_Call) Return(bytes []byte, err error) *Blobs_GetBlob_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Blobs_GetBlob_Call) RunAndReturn(run func(id digest.Digest) ([]byte, error)) *Blobs_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// InitUpload provides a mock function for the type Blobs
func (_mock *Blobs) InitUpload(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for InitUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Blobs_InitUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitUpload'
type Blobs_InitUpload_Call struct {
	*mock.Call
}

// InitUpload is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Blobs_Expecter) InitUpload(id interface{}) *Blobs_InitUpload_Call {
	return &Blobs_InitUpload_Call{Call: _e.mock.On("InitUpload", id)}
}

func (_c *Blobs_InitUpload_Call) Run(run func(id uuid.UUID)) *Blobs_InitUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Blobs_InitUpload_Call) Return(err error) *Blobs_InitUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Blobs_InitUpload_Call) RunAndReturn(run func(id uuid.UUID) error) *Blobs_InitUpload_Call {
	_c.Call.Return(run)
	return _c
}

// PutBlob provides a mock function for the type Blobs
func (_mock *Blobs) PutBlob(id digest.Digest, content []byte) error {
	ret := _mock.Called(id, content)

	if len(ret) == 0 {
		panic("no return value specified for PutBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest, []byte) error); ok {
		r0 = returnFunc(id, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Blobs_PutBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutBlob'
type Blobs_PutBlob_Call struct {
	*mock.Call
}

// PutBlob is a helper method to define mock.On call
//   - id digest.Digest
//   - content []byte
func (_e *Blobs_Expecter) PutBlob(id interface{}, content interface{}) *Blobs_PutBlob_Call {
	return &Blobs_PutBlob_Call{Call: _e.mock.On("PutBlob", id, content)}
}

func (_c *Blobs_PutBlob_Call) Run(run func(id digest.Digest, content []byte)) *Blobs_PutBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Blobs_PutBlob_Call) Return(err error) *Blobs_PutBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Blobs_PutBlob_Call) RunAndReturn(run func(id digest.Digest, content []byte) error) *Blobs_PutBlob_Call {
	_c.Call.Return(run)
	return _c
}

// StatBlob provides a mock function for the type Blobs
func (_mock *Blobs) StatBlob(id digest.Digest) (*store.BlobInfo, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for StatBlob")
	}

	var r0 *store.BlobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) (*store.BlobInfo, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) *store.BlobInfo); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(digest.Digest) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Blobs_StatBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatBlob'
type Blobs_StatBlob_Call struct {
	*mock.Call
}

// StatBlob is a helper method to define mock.On call
//   - id digest.Digest
func (_e *Blobs_Expecter) StatBlob(id interface{}) *Blobs_StatBlob_Call {
	return &Blobs_StatBlob_Call{Call: _e.mock.On("StatBlob", id)}
}

func (_c *Blobs_StatBlob_Call) Run(run func(id digest.Digest)) *Blobs_StatBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Blobs_StatBlob_Call) Return(blobInfo *store.BlobInfo, err error) *Blobs_StatBlob_Call {
	_c.Call.Return(blobInfo, err)
	return _c
}

func (_c *Blobs_StatBlob_Call) RunAndReturn(run func(id digest.Digest) (*store.BlobInfo, error)) *Blobs_StatBlob_Call {
	_c.Call.Return(run)
	return _c
}

// StatUpload provides a mock function for the type Blobs
func (_mock *Blobs) StatUpload(id uuid.UUID) (*store.BlobInfo, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for StatUpload")
	}

	var r0 *store.BlobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*store.BlobInfo, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *store.BlobInfo); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Blobs_StatUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatUpload'
type Blobs_StatUpload_Call struct {
	*mock.Call
}

// StatUpload is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Blobs_Expecter) StatUpload(id interface{}) *Blobs_StatUpload_Call {
	return &Blobs_StatUpload_Call{Call: _e.mock.On("StatUpload", id)}
}

func (_c *Blobs_StatUpload_Call) Run(run func(id uuid.UUID)) *Blobs_StatUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Blobs_StatUpload_Call) Return(blobInfo *store.BlobInfo, err error) *Blobs_StatUpload_Call {
	_c.Call.Return(blobInfo, err)
	return _c
}

func (_c *Blobs_StatUpload_Call) RunAndReturn(run func(id uuid.UUID) (*store.BlobInfo, error)) *Blobs_StatUpload_Call {
	_c.Call.Return(run)
	return _c
}

// UploadWriter provides a mock function for the type Blobs
func (_mock *Blobs) UploadWriter(id uuid.UUID) (io.WriteCloser, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for UploadWriter")
	}

	var r0 io.WriteCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (io.WriteCloser, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) io.WriteCloser); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Blobs_UploadWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadWriter'
type Blobs_UploadWriter_Call struct {
	*mock.Call
}

// UploadWriter is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Blobs_Expecter) UploadWriter(id interface{}) *Blobs_UploadWriter_Call {
	return &Blobs_UploadWriter_Call{Call: _e.mock.On("UploadWriter", id)}
}

func (_c *Blobs_UploadWriter_Call) Run(run func(id uuid.UUID)) *Blobs_UploadWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Blobs_UploadWriter_Call) Return(writeCloser io.WriteCloser, err error) *Blobs_UploadWriter_Call {
	_c.Call.Return(writeCloser, err)
	return _c
}

func (_c *Blobs_UploadWriter_Call) RunAndReturn(run func(id uuid.UUID) (io.WriteCloser, error)) *Blobs_UploadWriter_Call {
	_c.Call.Return(run)
	return _c
}
