// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"io"
	"iter"

	"github.com/opencontainers/go-digest"
	"github.com/robinkb/cascade/registry/store"
	mock "github.com/stretchr/testify/mock"
)

// NewMetadata creates a new instance of Metadata. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetadata(t interface {
	mock.TestingT
	Cleanup(func())
}) *Metadata {
	mock := &Metadata{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Metadata is an autogenerated mock type for the Metadata type
type Metadata struct {
	mock.Mock
}

type Metadata_Expecter struct {
	mock *mock.Mock
}

func (_m *Metadata) EXPECT() *Metadata_Expecter {
	return &Metadata_Expecter{mock: &_m.Mock}
}

// Blobs provides a mock function for the type Metadata
func (_mock *Metadata) Blobs() iter.Seq[digest.Digest] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Blobs")
	}

	var r0 iter.Seq[digest.Digest]
	if returnFunc, ok := ret.Get(0).(func() iter.Seq[digest.Digest]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[digest.Digest])
		}
	}
	return r0
}

// Metadata_Blobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Blobs'
type Metadata_Blobs_Call struct {
	*mock.Call
}

// Blobs is a helper method to define mock.On call
func (_e *Metadata_Expecter) Blobs() *Metadata_Blobs_Call {
	return &Metadata_Blobs_Call{Call: _e.mock.On("Blobs")}
}

func (_c *Metadata_Blobs_Call) Run(run func()) *Metadata_Blobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Metadata_Blobs_Call) Return(seq iter.Seq[digest.Digest]) *Metadata_Blobs_Call {
	_c.Call.Return(seq)
	return _c
}

func (_c *Metadata_Blobs_Call) RunAndReturn(run func() iter.Seq[digest.Digest]) *Metadata_Blobs_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRepository provides a mock function for the type Metadata
func (_mock *Metadata) CreateRepository(name string) (store.Repository, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepository")
	}

	var r0 store.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (store.Repository, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) store.Repository); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Metadata_CreateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRepository'
type Metadata_CreateRepository_Call struct {
	*mock.Call
}

// CreateRepository is a helper method to define mock.On call
//   - name string
func (_e *Metadata_Expecter) CreateRepository(name interface{}) *Metadata_CreateRepository_Call {
	return &Metadata_CreateRepository_Call{Call: _e.mock.On("CreateRepository", name)}
}

func (_c *Metadata_CreateRepository_Call) Run(run func(name string)) *Metadata_CreateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Metadata_CreateRepository_Call) Return(repository store.Repository, err error) *Metadata_CreateRepository_Call {
	_c.Call.Return(repository, err)
	return _c
}

func (_c *Metadata_CreateRepository_Call) RunAndReturn(run func(name string) (store.Repository, error)) *Metadata_CreateRepository_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRepository provides a mock function for the type Metadata
func (_mock *Metadata) DeleteRepository(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Metadata_DeleteRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRepository'
type Metadata_DeleteRepository_Call struct {
	*mock.Call
}

// DeleteRepository is a helper method to define mock.On call
//   - name string
func (_e *Metadata_Expecter) DeleteRepository(name interface{}) *Metadata_DeleteRepository_Call {
	return &Metadata_DeleteRepository_Call{Call: _e.mock.On("DeleteRepository", name)}
}

func (_c *Metadata_DeleteRepository_Call) Run(run func(name string)) *Metadata_DeleteRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Metadata_DeleteRepository_Call) Return(err error) *Metadata_DeleteRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Metadata_DeleteRepository_Call) RunAndReturn(run func(name string) error) *Metadata_DeleteRepository_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepository provides a mock function for the type Metadata
func (_mock *Metadata) GetRepository(name string) (store.Repository, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 store.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (store.Repository, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) store.Repository); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Metadata_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type Metadata_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
//   - name string
func (_e *Metadata_Expecter) GetRepository(name interface{}) *Metadata_GetRepository_Call {
	return &Metadata_GetRepository_Call{Call: _e.mock.On("GetRepository", name)}
}

func (_c *Metadata_GetRepository_Call) Run(run func(name string)) *Metadata_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Metadata_GetRepository_Call) Return(repository store.Repository, err error) *Metadata_GetRepository_Call {
	_c.Call.Return(repository, err)
	return _c
}

func (_c *Metadata_GetRepository_Call) RunAndReturn(run func(name string) (store.Repository, error)) *Metadata_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type Metadata
func (_mock *Metadata) Restore(r io.Reader) error {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader) error); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Metadata_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type Metadata_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - r io.Reader
func (_e *Metadata_Expecter) Restore(r interface{}) *Metadata_Restore_Call {
	return &Metadata_Restore_Call{Call: _e.mock.On("Restore", r)}
}

func (_c *Metadata_Restore_Call) Run(run func(r io.Reader)) *Metadata_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Metadata_Restore_Call) Return(err error) *Metadata_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Metadata_Restore_Call) RunAndReturn(run func(r io.Reader) error) *Metadata_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Snapshot provides a mock function for the type Metadata
func (_mock *Metadata) Snapshot(w io.Writer) error {
	ret := _mock.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer) error); ok {
		r0 = returnFunc(w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Metadata_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type Metadata_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
//   - w io.Writer
func (_e *Metadata_Expecter) Snapshot(w interface{}) *Metadata_Snapshot_Call {
	return &Metadata_Snapshot_Call{Call: _e.mock.On("Snapshot", w)}
}

func (_c *Metadata_Snapshot_Call) Run(run func(w io.Writer)) *Metadata_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Metadata_Snapshot_Call) Return(err error) *Metadata_Snapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Metadata_Snapshot_Call) RunAndReturn(run func(w io.Writer) error) *Metadata_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}
