// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"github.com/gofrs/uuid/v5"
	"github.com/opencontainers/go-digest"
	"github.com/robinkb/cascade/registry/store"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// DeleteBlob provides a mock function for the type Repository
func (_mock *Repository) DeleteBlob(id digest.Digest) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_DeleteBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlob'
type Repository_DeleteBlob_Call struct {
	*mock.Call
}

// DeleteBlob is a helper method to define mock.On call
//   - id digest.Digest
func (_e *Repository_Expecter) DeleteBlob(id interface{}) *Repository_DeleteBlob_Call {
	return &Repository_DeleteBlob_Call{Call: _e.mock.On("DeleteBlob", id)}
}

func (_c *Repository_DeleteBlob_Call) Run(run func(id digest.Digest)) *Repository_DeleteBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_DeleteBlob_Call) Return(err error) *Repository_DeleteBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_DeleteBlob_Call) RunAndReturn(run func(id digest.Digest) error) *Repository_DeleteBlob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteManifest provides a mock function for the type Repository
func (_mock *Repository) DeleteManifest(id digest.Digest) ([]digest.Digest, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManifest")
	}

	var r0 []digest.Digest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) ([]digest.Digest, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) []digest.Digest); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]digest.Digest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(digest.Digest) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_DeleteManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManifest'
type Repository_DeleteManifest_Call struct {
	*mock.Call
}

// DeleteManifest is a helper method to define mock.On call
//   - id digest.Digest
func (_e *Repository_Expecter) DeleteManifest(id interface{}) *Repository_DeleteManifest_Call {
	return &Repository_DeleteManifest_Call{Call: _e.mock.On("DeleteManifest", id)}
}

func (_c *Repository_DeleteManifest_Call) Run(run func(id digest.Digest)) *Repository_DeleteManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_DeleteManifest_Call) Return(digests []digest.Digest, err error) *Repository_DeleteManifest_Call {
	_c.Call.Return(digests, err)
	return _c
}

func (_c *Repository_DeleteManifest_Call) RunAndReturn(run func(id digest.Digest) ([]digest.Digest, error)) *Repository_DeleteManifest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function for the type Repository
func (_mock *Repository) DeleteTag(tag string) ([]digest.Digest, error) {
	ret := _mock.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 []digest.Digest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]digest.Digest, error)); ok {
		return returnFunc(tag)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []digest.Digest); ok {
		r0 = returnFunc(tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]digest.Digest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type Repository_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - tag string
func (_e *Repository_Expecter) DeleteTag(tag interface{}) *Repository_DeleteTag_Call {
	return &Repository_DeleteTag_Call{Call: _e.mock.On("DeleteTag", tag)}
}

func (_c *Repository_DeleteTag_Call) Run(run func(tag string)) *Repository_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_DeleteTag_Call) Return(digests []digest.Digest, err error) *Repository_DeleteTag_Call {
	_c.Call.Return(digests, err)
	return _c
}

func (_c *Repository_DeleteTag_Call) RunAndReturn(run func(tag string) ([]digest.Digest, error)) *Repository_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUploadSession provides a mock function for the type Repository
func (_mock *Repository) DeleteUploadSession(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUploadSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_DeleteUploadSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUploadSession'
type Repository_DeleteUploadSession_Call struct {
	*mock.Call
}

// DeleteUploadSession is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Repository_Expecter) DeleteUploadSession(id interface{}) *Repository_DeleteUploadSession_Call {
	return &Repository_DeleteUploadSession_Call{Call: _e.mock.On("DeleteUploadSession", id)}
}

func (_c *Repository_DeleteUploadSession_Call) Run(run func(id uuid.UUID)) *Repository_DeleteUploadSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_DeleteUploadSession_Call) Return(err error) *Repository_DeleteUploadSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_DeleteUploadSession_Call) RunAndReturn(run func(id uuid.UUID) error) *Repository_DeleteUploadSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlob provides a mock function for the type Repository
func (_mock *Repository) GetBlob(id digest.Digest) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type Repository_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - id digest.Digest
func (_e *Repository_Expecter) GetBlob(id interface{}) *Repository_GetBlob_Call {
	return &Repository_GetBlob_Call{Call: _e.mock.On("GetBlob", id)}
}

func (_c *Repository_GetBlob_Call) Run(run func(id digest.Digest)) *Repository_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_GetBlob_Call) Return(err error) *Repository_GetBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_GetBlob_Call) RunAndReturn(run func(id digest.Digest) error) *Repository_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// GetManifest provides a mock function for the type Repository
func (_mock *Repository) GetManifest(id digest.Digest) (store.Manifest, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetManifest")
	}

	var r0 store.Manifest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) (store.Manifest, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) store.Manifest); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(store.Manifest)
	}
	if returnFunc, ok := ret.Get(1).(func(digest.Digest) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManifest'
type Repository_GetManifest_Call struct {
	*mock.Call
}

// GetManifest is a helper method to define mock.On call
//   - id digest.Digest
func (_e *Repository_Expecter) GetManifest(id interface{}) *Repository_GetManifest_Call {
	return &Repository_GetManifest_Call{Call: _e.mock.On("GetManifest", id)}
}

func (_c *Repository_GetManifest_Call) Run(run func(id digest.Digest)) *Repository_GetManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_GetManifest_Call) Return(manifest store.Manifest, err error) *Repository_GetManifest_Call {
	_c.Call.Return(manifest, err)
	return _c
}

func (_c *Repository_GetManifest_Call) RunAndReturn(run func(id digest.Digest) (store.Manifest, error)) *Repository_GetManifest_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function for the type Repository
func (_mock *Repository) GetTag(tag string) (digest.Digest, error) {
	ret := _mock.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 digest.Digest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (digest.Digest, error)); ok {
		return returnFunc(tag)
	}
	if returnFunc, ok := ret.Get(0).(func(string) digest.Digest); ok {
		r0 = returnFunc(tag)
	} else {
		r0 = ret.Get(0).(digest.Digest)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type Repository_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
//   - tag string
func (_e *Repository_Expecter) GetTag(tag interface{}) *Repository_GetTag_Call {
	return &Repository_GetTag_Call{Call: _e.mock.On("GetTag", tag)}
}

func (_c *Repository_GetTag_Call) Run(run func(tag string)) *Repository_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_GetTag_Call) Return(digest1 digest.Digest, err error) *Repository_GetTag_Call {
	_c.Call.Return(digest1, err)
	return _c
}

func (_c *Repository_GetTag_Call) RunAndReturn(run func(tag string) (digest.Digest, error)) *Repository_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadSession provides a mock function for the type Repository
func (_mock *Repository) GetUploadSession(id uuid.UUID) (*store.UploadSession, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadSession")
	}

	var r0 *store.UploadSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*store.UploadSession, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *store.UploadSession); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.UploadSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_GetUploadSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadSession'
type Repository_GetUploadSession_Call struct {
	*mock.Call
}

// GetUploadSession is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *Repository_Expecter) GetUploadSession(id interface{}) *Repository_GetUploadSession_Call {
	return &Repository_GetUploadSession_Call{Call: _e.mock.On("GetUploadSession", id)}
}

func (_c *Repository_GetUploadSession_Call) Run(run func(id uuid.UUID)) *Repository_GetUploadSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_GetUploadSession_Call) Return(uploadSession *store.UploadSession, err error) *Repository_GetUploadSession_Call {
	_c.Call.Return(uploadSession, err)
	return _c
}

func (_c *Repository_GetUploadSession_Call) RunAndReturn(run func(id uuid.UUID) (*store.UploadSession, error)) *Repository_GetUploadSession_Call {
	_c.Call.Return(run)
	return _c
}

// ListReferrers provides a mock function for the type Repository
func (_mock *Repository) ListReferrers(subject digest.Digest) ([]digest.Digest, error) {
	ret := _mock.Called(subject)

	if len(ret) == 0 {
		panic("no return value specified for ListReferrers")
	}

	var r0 []digest.Digest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) ([]digest.Digest, error)); ok {
		return returnFunc(subject)
	}
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) []digest.Digest); ok {
		r0 = returnFunc(subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]digest.Digest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(digest.Digest) error); ok {
		r1 = returnFunc(subject)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_ListReferrers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReferrers'
type Repository_ListReferrers_Call struct {
	*mock.Call
}

// ListReferrers is a helper method to define mock.On call
//   - subject digest.Digest
func (_e *Repository_Expecter) ListReferrers(subject interface{}) *Repository_ListReferrers_Call {
	return &Repository_ListReferrers_Call{Call: _e.mock.On("ListReferrers", subject)}
}

func (_c *Repository_ListReferrers_Call) Run(run func(subject digest.Digest)) *Repository_ListReferrers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_ListReferrers_Call) Return(digests []digest.Digest, err error) *Repository_ListReferrers_Call {
	_c.Call.Return(digests, err)
	return _c
}

func (_c *Repository_ListReferrers_Call) RunAndReturn(run func(subject digest.Digest) ([]digest.Digest, error)) *Repository_ListReferrers_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type Repository
func (_mock *Repository) ListTags(count int, last string) ([]string, error) {
	ret := _mock.Called(count, last)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) ([]string, error)); ok {
		return returnFunc(count, last)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) []string); ok {
		r0 = returnFunc(count, last)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(count, last)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type Repository_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - count int
//   - last string
func (_e *Repository_Expecter) ListTags(count interface{}, last interface{}) *Repository_ListTags_Call {
	return &Repository_ListTags_Call{Call: _e.mock.On("ListTags", count, last)}
}

func (_c *Repository_ListTags_Call) Run(run func(count int, last string)) *Repository_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_ListTags_Call) Return(strings []string, err error) *Repository_ListTags_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Repository_ListTags_Call) RunAndReturn(run func(count int, last string) ([]string, error)) *Repository_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// PutBlob provides a mock function for the type Repository
func (_mock *Repository) PutBlob(id digest.Digest) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for PutBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_PutBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutBlob'
type Repository_PutBlob_Call struct {
	*mock.Call
}

// PutBlob is a helper method to define mock.On call
//   - id digest.Digest
func (_e *Repository_Expecter) PutBlob(id interface{}) *Repository_PutBlob_Call {
	return &Repository_PutBlob_Call{Call: _e.mock.On("PutBlob", id)}
}

func (_c *Repository_PutBlob_Call) Run(run func(id digest.Digest)) *Repository_PutBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_PutBlob_Call) Return(err error) *Repository_PutBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_PutBlob_Call) RunAndReturn(run func(id digest.Digest) error) *Repository_PutBlob_Call {
	_c.Call.Return(run)
	return _c
}

// PutManifest provides a mock function for the type Repository
func (_mock *Repository) PutManifest(id digest.Digest, meta store.Manifest, refs store.References) error {
	ret := _mock.Called(id, meta, refs)

	if len(ret) == 0 {
		panic("no return value specified for PutManifest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(digest.Digest, store.Manifest, store.References) error); ok {
		r0 = returnFunc(id, meta, refs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_PutManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutManifest'
type Repository_PutManifest_Call struct {
	*mock.Call
}

// PutManifest is a helper method to define mock.On call
//   - id digest.Digest
//   - meta store.Manifest
//   - refs store.References
func (_e *Repository_Expecter) PutManifest(id interface{}, meta interface{}, refs interface{}) *Repository_PutManifest_Call {
	return &Repository_PutManifest_Call{Call: _e.mock.On("PutManifest", id, meta, refs)}
}

func (_c *Repository_PutManifest_Call) Run(run func(id digest.Digest, meta store.Manifest, refs store.References)) *Repository_PutManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 digest.Digest
		if args[0] != nil {
			arg0 = args[0].(digest.Digest)
		}
		var arg1 store.Manifest
		if args[1] != nil {
			arg1 = args[1].(store.Manifest)
		}
		var arg2 store.References
		if args[2] != nil {
			arg2 = args[2].(store.References)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_PutManifest_Call) Return(err error) *Repository_PutManifest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_PutManifest_Call) RunAndReturn(run func(id digest.Digest, meta store.Manifest, refs store.References) error) *Repository_PutManifest_Call {
	_c.Call.Return(run)
	return _c
}

// PutTag provides a mock function for the type Repository
func (_mock *Repository) PutTag(tag string, digest1 digest.Digest) error {
	ret := _mock.Called(tag, digest1)

	if len(ret) == 0 {
		panic("no return value specified for PutTag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, digest.Digest) error); ok {
		r0 = returnFunc(tag, digest1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_PutTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutTag'
type Repository_PutTag_Call struct {
	*mock.Call
}

// PutTag is a helper method to define mock.On call
//   - tag string
//   - digest1 digest.Digest
func (_e *Repository_Expecter) PutTag(tag interface{}, digest1 interface{}) *Repository_PutTag_Call {
	return &Repository_PutTag_Call{Call: _e.mock.On("PutTag", tag, digest1)}
}

func (_c *Repository_PutTag_Call) Run(run func(tag string, digest1 digest.Digest)) *Repository_PutTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 digest.Digest
		if args[1] != nil {
			arg1 = args[1].(digest.Digest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_PutTag_Call) Return(err error) *Repository_PutTag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_PutTag_Call) RunAndReturn(run func(tag string, digest1 digest.Digest) error) *Repository_PutTag_Call {
	_c.Call.Return(run)
	return _c
}

// PutUploadSession provides a mock function for the type Repository
func (_mock *Repository) PutUploadSession(session *store.UploadSession) error {
	ret := _mock.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for PutUploadSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*store.UploadSession) error); ok {
		r0 = returnFunc(session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_PutUploadSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutUploadSession'
type Repository_PutUploadSession_Call struct {
	*mock.Call
}

// PutUploadSession is a helper method to define mock.On call
//   - session *store.UploadSession
func (_e *Repository_Expecter) PutUploadSession(session interface{}) *Repository_PutUploadSession_Call {
	return &Repository_PutUploadSession_Call{Call: _e.mock.On("PutUploadSession", session)}
}

func (_c *Repository_PutUploadSession_Call) Run(run func(session *store.UploadSession)) *Repository_PutUploadSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *store.UploadSession
		if args[0] != nil {
			arg0 = args[0].(*store.UploadSession)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_PutUploadSession_Call) Return(err error) *Repository_PutUploadSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_PutUploadSession_Call) RunAndReturn(run func(session *store.UploadSession) error) *Repository_PutUploadSession_Call {
	_c.Call.Return(run)
	return _c
}
