// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package registry

import (
	"github.com/robinkb/cascade/registry/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// CreateRepository provides a mock function for the type Service
func (_mock *Service) CreateRepository(name string) (repository.Service, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepository")
	}

	var r0 repository.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (repository.Service, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) repository.Service); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_CreateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRepository'
type Service_CreateRepository_Call struct {
	*mock.Call
}

// CreateRepository is a helper method to define mock.On call
//   - name string
func (_e *Service_Expecter) CreateRepository(name interface{}) *Service_CreateRepository_Call {
	return &Service_CreateRepository_Call{Call: _e.mock.On("CreateRepository", name)}
}

func (_c *Service_CreateRepository_Call) Run(run func(name string)) *Service_CreateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_CreateRepository_Call) Return(service repository.Service, err error) *Service_CreateRepository_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *Service_CreateRepository_Call) RunAndReturn(run func(name string) (repository.Service, error)) *Service_CreateRepository_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRepository provides a mock function for the type Service
func (_mock *Service) DeleteRepository(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_DeleteRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRepository'
type Service_DeleteRepository_Call struct {
	*mock.Call
}

// DeleteRepository is a helper method to define mock.On call
//   - name string
func (_e *Service_Expecter) DeleteRepository(name interface{}) *Service_DeleteRepository_Call {
	return &Service_DeleteRepository_Call{Call: _e.mock.On("DeleteRepository", name)}
}

func (_c *Service_DeleteRepository_Call) Run(run func(name string)) *Service_DeleteRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_DeleteRepository_Call) Return(err error) *Service_DeleteRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_DeleteRepository_Call) RunAndReturn(run func(name string) error) *Service_DeleteRepository_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepository provides a mock function for the type Service
func (_mock *Service) GetRepository(name string) (repository.Service, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 repository.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (repository.Service, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) repository.Service); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type Service_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
//   - name string
func (_e *Service_Expecter) GetRepository(name interface{}) *Service_GetRepository_Call {
	return &Service_GetRepository_Call{Call: _e.mock.On("GetRepository", name)}
}

func (_c *Service_GetRepository_Call) Run(run func(name string)) *Service_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_GetRepository_Call) Return(service repository.Service, err error) *Service_GetRepository_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *Service_GetRepository_Call) RunAndReturn(run func(name string) (repository.Service, error)) *Service_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// ListRepositories provides a mock function for the type Service
func (_mock *Service) ListRepositories(count int, last string) ([]string, error) {
	ret := _mock.Called(count, last)

	if len(ret) == 0 {
		panic("no return value specified for ListRepositories")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) ([]string, error)); ok {
		return returnFunc(count, last)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) []string); ok {
		r0 = returnFunc(count, last)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(count, last)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_ListRepositories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRepositories'
type Service_ListRepositories_Call struct {
	*mock.Call
}

// ListRepositories is a helper method to define mock.On call
//   - count int
//   - last string
func (_e *Service_Expecter) ListRepositories(count interface{}, last interface{}) *Service_ListRepositories_Call {
	return &Service_ListRepositories_Call{Call: _e.mock.On("ListRepositories", count, last)}
}

func (_c *Service_ListRepositories_Call) Run(run func(count int, last string)) *Service_ListRepositories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_ListRepositories_Call) Return(strings []string, err error) *Service_ListRepositories_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Service_ListRepositories_Call) RunAndReturn(run func(count int, last string) ([]string, error)) *Service_ListRepositories_Call {
	_c.Call.Return(run)
	return _c
}
