name: cascade

services:
  node1:
    image: ghcr.io/robinkb/cascade:latest
    build: ../../
    environment:
      CASCADE_RAFT_ID: 1
      CASCADE_RAFT_HOST: node1
      CASCADE_RAFT_PEERS: 1:node1:3000,2:node2:3000,3:node3:3000

  node2:
    image: ghcr.io/robinkb/cascade:latest
    build: ../../
    environment:
      CASCADE_RAFT_ID: 2
      CASCADE_RAFT_HOST: node2
      CASCADE_RAFT_PEERS: 1:node1:3000,2:node2:3000,3:node3:3000

  node3:
    image: ghcr.io/robinkb/cascade:latest
    build: ../../
    environment:
      CASCADE_RAFT_ID: 3
      CASCADE_RAFT_HOST: node3
      CASCADE_RAFT_PEERS: 1:node1:3000,2:node2:3000,3:node3:3000

  lb:
    image: docker.io/haproxytech/haproxy-alpine:3.3.6
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true
        bind:
          selinux: Z
    depends_on:
      - node1
      - node2
      - node3

  ui:
    image: docker.io/quiq/registry-ui:0.12.0
    environment:
      REGISTRY_HOSTNAME: lb:5000
      REGISTRY_INSECURE: true
      ACCESS_CONTROL_ANYONE_CAN_DELETE_TAGS: true
    ports:
      - 8000:8000
    depends_on:
      - lb
