version: "2"
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/robinkb/cascade
linters:
  exclusions:
    paths:
      - cluster/raft/qwal/example_test.go
      - cluster/raft/qwal/example_dump_test.go
