# Collect all of the mocks under the `testing/mock` package.
# Easy to find and import them all.
dir: testing/mock/{{ .SrcPackageName }}
filename: "{{ snakecase .InterfaceName}}.go"
structname: "{{ .InterfaceName }}"
pkgname: "{{ .SrcPackageName }}"
template: testify
# Explicitly select with interfaces to generate mocks for.
packages:
  github.com/robinkb/cascade/cluster/raft:
    interfaces:
      Node:
  github.com/robinkb/cascade/registry:
    interfaces:
      Service:
  github.com/robinkb/cascade/registry/repository:
    interfaces:
      Service:
  github.com/robinkb/cascade/registry/store:
    interfaces:
      Blobs:
      Metadata:
      Repository:
