# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set:
  - errexit
  - nounset
  - pipefail

tasks:
  # Public tasks
  clean:
    desc: remove all build artifacts
    cmd: rm -rf out/

  build:binary:
    desc: compile the main binary
    deps:
      - task: out-dir
    cmd: go build -o out/ ./cmd/cascade-registry

  build:container:
    desc: build container
    cmd: podman build -t cascade-registry:dev -f Dockerfile .
    sources:
      - Dockerfile
      - "**/*.go"
      - go.mod
      - go.sum

  compose:
    desc: start a cluster of registries
    cmds:
      - defer: podman compose -f hack/compose/compose.yaml down
      - cmd: podman compose -f hack/compose/compose.yaml up

  kind:create:
    desc: create a kind cluster with registry installed as static pods
    summary: |
      Creates a Kubernetes cluster using Kind, with Cascade deployed to the control plane nodes
      as a static pod.

      Troubleshooting:
        * kind complains about setting systemd property "Delegate=yes":
          -> This is usually set by default, but your desktop environment may be overriding it.
             Find out your desktop environment's systemd service with `cat /proc/self/cgroup`.
             It should be the last part of the path. Then create an override for it:

             $ systemctl --user edit org.gnome.Shell@user.service # If you use GNOME shell
             [Service]
             Delegate=cpu memory pids

        * kind fails to bring up all nodes:
          -> Use `podman exec <container_name> journalctl -u kubelet` to inspect the logs
             of that node's Kubelet. If it shows errors like "inotify_init: too many open files",
             the inotify limit must be raised. Create a `.conf` file under `/etc/sysctl.d`
             with the following content:

             fs.inotify.max_user_watches=524288
             fs.inotify.max_user_instances=512

             Then reload sysctl with `sudo sysctl --system`.
    deps:
      - task: build:container
    cmds:
      - cmd: kind create cluster --config hack/kind/config.yaml
        if: if kind get clusters --quiet | grep -q cascade-testing; then exit 1; fi
      - cmd: kind load docker-image --name cascade-testing localhost/cascade-registry:dev

  kind:delete:
    desc: deletes kind cluster provisioned by kind:create
    cmd: kind delete clusters cascade-testing

  test:
    desc: run tests
    cmd: go test ./... -timeout=20s

  coverage:
    desc: calculate the total test coverage
    deps:
      - task: out-dir
    cmds:
      - cmd: go list ./... | grep -v 'mock' > out/cover-packages.txt
      - cmd: go test ./... -timeout=15s -coverpkg=$(cat out/cover-packages.txt | paste -sd ,) -coverprofile=out/cover.txt > /dev/null
      - cmd: go tool cover -func=out/cover.txt | grep "total:" | awk '{print $3}'

  generate:
    desc: run all generate tasks
    deps:
      - task: generate:mock
      - task: generate:protobuf

  generate:mock:
    desc: generate mocks
    cmd: go tool mockery --log-level error
    sources:
      - "**/*.go"
      - exclude: "**/*_test.go"
    generates:
      - testing/*/mock/*.go

  generate:protobuf:
    desc: generate types from protobuf schemas
    cmd: buf generate
    sources:
      - "**/*.proto"
    generates:
      - "**/*.pb.go"

  lint:
    desc: run static quality checks
    cmds:
      - cmd: go mod tidy -diff
      - cmd: buf format --write
      - cmd: golangci-lint run ./... --fix

  pr:
    desc: run checks to validate a pull request
    deps:
      - task: generate
      - task: lint
      - task: test
    cmd: git diff --exit-code

  # Internal tasks
  out-dir:
    desc: ensures that the "out" dir exists for writing build artifacts
    cmd: mkdir -p out
    internal: true
    silent: true
