# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set:
  - errexit
  - nounset
  - pipefail

tasks:
  # Public tasks
  clean:
    desc: remove all build artifacts
    cmd: rm -rf out/

  build:
    desc: compile the main binary
    deps:
      - task: out-dir
    cmd: go build -o out/ ./cmd/cascade-registry

  compose:
    desc: start a cluster of registries
    cmds:
      - defer: podman compose -f compose/compose.yaml down
      - cmd: podman compose -f compose/compose.yaml up

  test:
    desc: run tests
    cmd: go test ./... -timeout=20s

  coverage:
    desc: calculate the total test coverage
    deps:
      - task: out-dir
    cmds:
      - cmd: go list ./... | grep -v 'mock' > out/cover-packages.txt
      - cmd: go test ./... -timeout=15s -coverpkg=$(cat out/cover-packages.txt | paste -sd ,) -coverprofile=out/cover.txt > /dev/null
      - cmd: go tool cover -func=out/cover.txt | grep "total:" | awk '{print $3}'

  generate:
    desc: run all generate tasks
    deps:
      - task: generate:mock
      - task: generate:protobuf

  generate:mock:
    desc: generate mocks
    cmd: go tool mockery --log-level error
    sources:
      - "**/*.go"
      - exclude: "**/*_test.go"
    generates:
      - testing/*/mock/*.go

  generate:protobuf:
    desc: generate types from protobuf schemas
    cmd: buf generate
    sources:
      - "**/*.proto"
    generates:
      - "**/*.pb.go"

  lint:
    desc: run static quality checks
    cmds:
      - cmd: go mod tidy -diff
      - cmd: buf format --write
      - cmd: golangci-lint run ./... --fix

  pr:
    desc: run checks to validate a pull request
    deps:
      - task: generate
      - task: lint
      - task: test
    cmd: git diff --exit-code

  # Internal tasks
  out-dir:
    desc: ensures that the "out" dir exists for writing build artifacts
    cmd: mkdir -p out
    internal: true
    silent: true
