// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package raft

import (
	"context"
	"net/netip"

	"github.com/robinkb/cascade/cluster"
	mock "github.com/stretchr/testify/mock"
	"go.etcd.io/raft/v3"
	"go.etcd.io/raft/v3/raftpb"
)

// NewNode creates a new instance of Node. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *Node {
	mock := &Node{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Node is an autogenerated mock type for the Node type
type Node struct {
	mock.Mock
}

type Node_Expecter struct {
	mock *mock.Mock
}

func (_m *Node) EXPECT() *Node_Expecter {
	return &Node_Expecter{mock: &_m.Mock}
}

// AddNode provides a mock function for the type Node
func (_mock *Node) AddNode(ctx context.Context, peer cluster.Peer) error {
	ret := _mock.Called(ctx, peer)

	if len(ret) == 0 {
		panic("no return value specified for AddNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cluster.Peer) error); ok {
		r0 = returnFunc(ctx, peer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_AddNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNode'
type Node_AddNode_Call struct {
	*mock.Call
}

// AddNode is a helper method to define mock.On call
//   - ctx context.Context
//   - peer cluster.Peer
func (_e *Node_Expecter) AddNode(ctx interface{}, peer interface{}) *Node_AddNode_Call {
	return &Node_AddNode_Call{Call: _e.mock.On("AddNode", ctx, peer)}
}

func (_c *Node_AddNode_Call) Run(run func(ctx context.Context, peer cluster.Peer)) *Node_AddNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cluster.Peer
		if args[1] != nil {
			arg1 = args[1].(cluster.Peer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Node_AddNode_Call) Return(err error) *Node_AddNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_AddNode_Call) RunAndReturn(run func(ctx context.Context, peer cluster.Peer) error) *Node_AddNode_Call {
	_c.Call.Return(run)
	return _c
}

// AddrPort provides a mock function for the type Node
func (_mock *Node) AddrPort() netip.AddrPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddrPort")
	}

	var r0 netip.AddrPort
	if returnFunc, ok := ret.Get(0).(func() netip.AddrPort); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(netip.AddrPort)
	}
	return r0
}

// Node_AddrPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddrPort'
type Node_AddrPort_Call struct {
	*mock.Call
}

// AddrPort is a helper method to define mock.On call
func (_e *Node_Expecter) AddrPort() *Node_AddrPort_Call {
	return &Node_AddrPort_Call{Call: _e.mock.On("AddrPort")}
}

func (_c *Node_AddrPort_Call) Run(run func()) *Node_AddrPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_AddrPort_Call) Return(addrPort netip.AddrPort) *Node_AddrPort_Call {
	_c.Call.Return(addrPort)
	return _c
}

func (_c *Node_AddrPort_Call) RunAndReturn(run func() netip.AddrPort) *Node_AddrPort_Call {
	_c.Call.Return(run)
	return _c
}

// AsPeer provides a mock function for the type Node
func (_mock *Node) AsPeer() cluster.Peer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AsPeer")
	}

	var r0 cluster.Peer
	if returnFunc, ok := ret.Get(0).(func() cluster.Peer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(cluster.Peer)
	}
	return r0
}

// Node_AsPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsPeer'
type Node_AsPeer_Call struct {
	*mock.Call
}

// AsPeer is a helper method to define mock.On call
func (_e *Node_Expecter) AsPeer() *Node_AsPeer_Call {
	return &Node_AsPeer_Call{Call: _e.mock.On("AsPeer")}
}

func (_c *Node_AsPeer_Call) Run(run func()) *Node_AsPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_AsPeer_Call) Return(peer cluster.Peer) *Node_AsPeer_Call {
	_c.Call.Return(peer)
	return _c
}

func (_c *Node_AsPeer_Call) RunAndReturn(run func() cluster.Peer) *Node_AsPeer_Call {
	_c.Call.Return(run)
	return _c
}

// Bootstrap provides a mock function for the type Node
func (_mock *Node) Bootstrap(peers ...cluster.Peer) {
	if len(peers) > 0 {
		_mock.Called(peers)
	} else {
		_mock.Called()
	}

	return
}

// Node_Bootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bootstrap'
type Node_Bootstrap_Call struct {
	*mock.Call
}

// Bootstrap is a helper method to define mock.On call
//   - peers ...cluster.Peer
func (_e *Node_Expecter) Bootstrap(peers ...interface{}) *Node_Bootstrap_Call {
	return &Node_Bootstrap_Call{Call: _e.mock.On("Bootstrap",
		append([]interface{}{}, peers...)...)}
}

func (_c *Node_Bootstrap_Call) Run(run func(peers ...cluster.Peer)) *Node_Bootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []cluster.Peer
		var variadicArgs []cluster.Peer
		if len(args) > 0 {
			variadicArgs = args[0].([]cluster.Peer)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Node_Bootstrap_Call) Return() *Node_Bootstrap_Call {
	_c.Call.Return()
	return _c
}

func (_c *Node_Bootstrap_Call) RunAndReturn(run func(peers ...cluster.Peer)) *Node_Bootstrap_Call {
	_c.Run(run)
	return _c
}

// Handle provides a mock function for the type Node
func (_mock *Node) Handle(p cluster.Proposal, f cluster.HandlerFunc) {
	_mock.Called(p, f)
	return
}

// Node_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Node_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - p cluster.Proposal
//   - f cluster.HandlerFunc
func (_e *Node_Expecter) Handle(p interface{}, f interface{}) *Node_Handle_Call {
	return &Node_Handle_Call{Call: _e.mock.On("Handle", p, f)}
}

func (_c *Node_Handle_Call) Run(run func(p cluster.Proposal, f cluster.HandlerFunc)) *Node_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cluster.Proposal
		if args[0] != nil {
			arg0 = args[0].(cluster.Proposal)
		}
		var arg1 cluster.HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(cluster.HandlerFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Node_Handle_Call) Return() *Node_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *Node_Handle_Call) RunAndReturn(run func(p cluster.Proposal, f cluster.HandlerFunc)) *Node_Handle_Call {
	_c.Run(run)
	return _c
}

// Name provides a mock function for the type Node
func (_mock *Node) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Node_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Node_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Node_Expecter) Name() *Node_Name_Call {
	return &Node_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Node_Name_Call) Run(run func()) *Node_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Name_Call) Return(s string) *Node_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Node_Name_Call) RunAndReturn(run func() string) *Node_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NodeID provides a mock function for the type Node
func (_mock *Node) NodeID() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeID")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// Node_NodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeID'
type Node_NodeID_Call struct {
	*mock.Call
}

// NodeID is a helper method to define mock.On call
func (_e *Node_Expecter) NodeID() *Node_NodeID_Call {
	return &Node_NodeID_Call{Call: _e.mock.On("NodeID")}
}

func (_c *Node_NodeID_Call) Run(run func()) *Node_NodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_NodeID_Call) Return(v uint64) *Node_NodeID_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Node_NodeID_Call) RunAndReturn(run func() uint64) *Node_NodeID_Call {
	_c.Call.Return(run)
	return _c
}

// Propose provides a mock function for the type Node
func (_mock *Node) Propose(p cluster.Proposal) error {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Propose")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(cluster.Proposal) error); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_Propose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Propose'
type Node_Propose_Call struct {
	*mock.Call
}

// Propose is a helper method to define mock.On call
//   - p cluster.Proposal
func (_e *Node_Expecter) Propose(p interface{}) *Node_Propose_Call {
	return &Node_Propose_Call{Call: _e.mock.On("Propose", p)}
}

func (_c *Node_Propose_Call) Run(run func(p cluster.Proposal)) *Node_Propose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cluster.Proposal
		if args[0] != nil {
			arg0 = args[0].(cluster.Proposal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Node_Propose_Call) Return(err error) *Node_Propose_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_Propose_Call) RunAndReturn(run func(p cluster.Proposal) error) *Node_Propose_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type Node
func (_mock *Node) Receive(m *raftpb.Message) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*raftpb.Message) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type Node_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - m *raftpb.Message
func (_e *Node_Expecter) Receive(m interface{}) *Node_Receive_Call {
	return &Node_Receive_Call{Call: _e.mock.On("Receive", m)}
}

func (_c *Node_Receive_Call) Run(run func(m *raftpb.Message)) *Node_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *raftpb.Message
		if args[0] != nil {
			arg0 = args[0].(*raftpb.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Node_Receive_Call) Return(err error) *Node_Receive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_Receive_Call) RunAndReturn(run func(m *raftpb.Message) error) *Node_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNode provides a mock function for the type Node
func (_mock *Node) RemoveNode(ctx context.Context, peer cluster.Peer) error {
	ret := _mock.Called(ctx, peer)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cluster.Peer) error); ok {
		r0 = returnFunc(ctx, peer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_RemoveNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNode'
type Node_RemoveNode_Call struct {
	*mock.Call
}

// RemoveNode is a helper method to define mock.On call
//   - ctx context.Context
//   - peer cluster.Peer
func (_e *Node_Expecter) RemoveNode(ctx interface{}, peer interface{}) *Node_RemoveNode_Call {
	return &Node_RemoveNode_Call{Call: _e.mock.On("RemoveNode", ctx, peer)}
}

func (_c *Node_RemoveNode_Call) Run(run func(ctx context.Context, peer cluster.Peer)) *Node_RemoveNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cluster.Peer
		if args[1] != nil {
			arg1 = args[1].(cluster.Peer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Node_RemoveNode_Call) Return(err error) *Node_RemoveNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_RemoveNode_Call) RunAndReturn(run func(ctx context.Context, peer cluster.Peer) error) *Node_RemoveNode_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type Node
func (_mock *Node) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Node_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *Node_Expecter) Run() *Node_Run_Call {
	return &Node_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *Node_Run_Call) Run(run func()) *Node_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Run_Call) Return(err error) *Node_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_Run_Call) RunAndReturn(run func() error) *Node_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type Node
func (_mock *Node) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type Node_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *Node_Expecter) Shutdown() *Node_Shutdown_Call {
	return &Node_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *Node_Shutdown_Call) Run(run func()) *Node_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Shutdown_Call) Return(err error) *Node_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_Shutdown_Call) RunAndReturn(run func() error) *Node_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type Node
func (_mock *Node) Status() raft.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 raft.Status
	if returnFunc, ok := ret.Get(0).(func() raft.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(raft.Status)
	}
	return r0
}

// Node_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type Node_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *Node_Expecter) Status() *Node_Status_Call {
	return &Node_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *Node_Status_Call) Run(run func()) *Node_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Status_Call) Return(status raft.Status) *Node_Status_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *Node_Status_Call) RunAndReturn(run func() raft.Status) *Node_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Tick provides a mock function for the type Node
func (_mock *Node) Tick() {
	_mock.Called()
	return
}

// Node_Tick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tick'
type Node_Tick_Call struct {
	*mock.Call
}

// Tick is a helper method to define mock.On call
func (_e *Node_Expecter) Tick() *Node_Tick_Call {
	return &Node_Tick_Call{Call: _e.mock.On("Tick")}
}

func (_c *Node_Tick_Call) Run(run func()) *Node_Tick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Tick_Call) Return() *Node_Tick_Call {
	_c.Call.Return()
	return _c
}

func (_c *Node_Tick_Call) RunAndReturn(run func()) *Node_Tick_Call {
	_c.Run(run)
	return _c
}
