package testing

import (
	crand "crypto/rand"
	"encoding/json"
	"fmt"
	"math/rand/v2"
	"slices"
	"strings"

	"github.com/moby/moby/pkg/namesgenerator"
	"github.com/opencontainers/go-digest"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
	"github.com/robinkb/cascade-registry"
)

func RandomName() string {
	return strings.Replace(namesgenerator.GetRandomName(0), "_", "/", -1)
}

func RandomContents(length int64) []byte {
	data := make([]byte, length)
	crand.Read(data)
	return data
}

func RandomDigest() digest.Digest {
	return digest.FromBytes(RandomContents(32))
}

func RandomManifest() (*cascade.Manifest, digest.Digest) {
	content, _ := json.Marshal(v1.Manifest{
		MediaType: v1.MediaTypeImageManifest,
	})
	id := digest.FromBytes(content)
	manifest, _ := cascade.NewManifest(content)
	return manifest, id
}

func RandomManifestWithSubject(subject *cascade.Manifest) (*cascade.Manifest, digest.Digest) {
	subjDigest := digest.FromBytes(subject.Bytes())
	content, _ := json.Marshal(v1.Manifest{
		MediaType: v1.MediaTypeImageManifest,
		Subject: &v1.Descriptor{
			MediaType: subject.MediaType,
			Digest:    subjDigest,
		},
		Annotations: map[string]string{
			// Small amount of random content to make sure that
			// every generated manifest has a unique digest.
			"random": string(RandomContents(32)),
		},
	})
	digest := digest.FromBytes(content)
	manifest, _ := cascade.NewManifest(content)
	return manifest, digest
}

func RandomBlob(length int64) (id digest.Digest, content []byte) {
	content = RandomContents(length)
	id = digest.FromBytes(content)
	return
}

func RandomVersion() string {
	var major, minor, patch int

	major = rand.IntN(5)
	minor = rand.IntN(20)
	patch = rand.IntN(60)

	return fmt.Sprintf("v%d.%d.%d", major, minor, patch)
}

func RandomTags(count int) (tags []string) {
	var version string

	for range count {
		for {
			version = RandomVersion()

			// Make sure that there are no duplicates. The registry deduplicates tags.
			// If every tag in the returned slice is pushed to the registry,
			// and the returned list from RandomTags contains duplicate tags,
			// listing the tags from the registry will return fewer elements
			// than were generated by this function. That makes tests flaky.
			if !slices.Contains(tags, version) {
				tags = append(tags, RandomVersion())
				break
			}
		}
	}

	slices.Sort(tags)

	return
}
