// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"io"

	"github.com/opencontainers/go-digest"
	"github.com/robinkb/cascade/registry/repository"
	"github.com/robinkb/cascade/registry/store"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// AppendUpload provides a mock function for the type Service
func (_mock *Service) AppendUpload(sessionID string, r io.Reader, offset int64) error {
	ret := _mock.Called(sessionID, r, offset)

	if len(ret) == 0 {
		panic("no return value specified for AppendUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, io.Reader, int64) error); ok {
		r0 = returnFunc(sessionID, r, offset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_AppendUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendUpload'
type Service_AppendUpload_Call struct {
	*mock.Call
}

// AppendUpload is a helper method to define mock.On call
//   - sessionID string
//   - r io.Reader
//   - offset int64
func (_e *Service_Expecter) AppendUpload(sessionID interface{}, r interface{}, offset interface{}) *Service_AppendUpload_Call {
	return &Service_AppendUpload_Call{Call: _e.mock.On("AppendUpload", sessionID, r, offset)}
}

func (_c *Service_AppendUpload_Call) Run(run func(sessionID string, r io.Reader, offset int64)) *Service_AppendUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_AppendUpload_Call) Return(err error) *Service_AppendUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_AppendUpload_Call) RunAndReturn(run func(sessionID string, r io.Reader, offset int64) error) *Service_AppendUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CloseUpload provides a mock function for the type Service
func (_mock *Service) CloseUpload(id string, digest string) error {
	ret := _mock.Called(id, digest)

	if len(ret) == 0 {
		panic("no return value specified for CloseUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(id, digest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_CloseUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseUpload'
type Service_CloseUpload_Call struct {
	*mock.Call
}

// CloseUpload is a helper method to define mock.On call
//   - id string
//   - digest string
func (_e *Service_Expecter) CloseUpload(id interface{}, digest interface{}) *Service_CloseUpload_Call {
	return &Service_CloseUpload_Call{Call: _e.mock.On("CloseUpload", id, digest)}
}

func (_c *Service_CloseUpload_Call) Run(run func(id string, digest string)) *Service_CloseUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_CloseUpload_Call) Return(err error) *Service_CloseUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_CloseUpload_Call) RunAndReturn(run func(id string, digest string) error) *Service_CloseUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlob provides a mock function for the type Service
func (_mock *Service) DeleteBlob(digest string) error {
	ret := _mock.Called(digest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(digest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_DeleteBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlob'
type Service_DeleteBlob_Call struct {
	*mock.Call
}

// DeleteBlob is a helper method to define mock.On call
//   - digest string
func (_e *Service_Expecter) DeleteBlob(digest interface{}) *Service_DeleteBlob_Call {
	return &Service_DeleteBlob_Call{Call: _e.mock.On("DeleteBlob", digest)}
}

func (_c *Service_DeleteBlob_Call) Run(run func(digest string)) *Service_DeleteBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_DeleteBlob_Call) Return(err error) *Service_DeleteBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_DeleteBlob_Call) RunAndReturn(run func(digest string) error) *Service_DeleteBlob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteManifest provides a mock function for the type Service
func (_mock *Service) DeleteManifest(reference string) error {
	ret := _mock.Called(reference)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManifest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(reference)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_DeleteManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManifest'
type Service_DeleteManifest_Call struct {
	*mock.Call
}

// DeleteManifest is a helper method to define mock.On call
//   - reference string
func (_e *Service_Expecter) DeleteManifest(reference interface{}) *Service_DeleteManifest_Call {
	return &Service_DeleteManifest_Call{Call: _e.mock.On("DeleteManifest", reference)}
}

func (_c *Service_DeleteManifest_Call) Run(run func(reference string)) *Service_DeleteManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_DeleteManifest_Call) Return(err error) *Service_DeleteManifest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_DeleteManifest_Call) RunAndReturn(run func(reference string) error) *Service_DeleteManifest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function for the type Service
func (_mock *Service) DeleteTag(tag string) error {
	ret := _mock.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type Service_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - tag string
func (_e *Service_Expecter) DeleteTag(tag interface{}) *Service_DeleteTag_Call {
	return &Service_DeleteTag_Call{Call: _e.mock.On("DeleteTag", tag)}
}

func (_c *Service_DeleteTag_Call) Run(run func(tag string)) *Service_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_DeleteTag_Call) Return(err error) *Service_DeleteTag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_DeleteTag_Call) RunAndReturn(run func(tag string) error) *Service_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlob provides a mock function for the type Service
func (_mock *Service) GetBlob(digest string) (io.Reader, error) {
	ret := _mock.Called(digest)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 io.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (io.Reader, error)); ok {
		return returnFunc(digest)
	}
	if returnFunc, ok := ret.Get(0).(func(string) io.Reader); ok {
		r0 = returnFunc(digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type Service_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - digest string
func (_e *Service_Expecter) GetBlob(digest interface{}) *Service_GetBlob_Call {
	return &Service_GetBlob_Call{Call: _e.mock.On("GetBlob", digest)}
}

func (_c *Service_GetBlob_Call) Run(run func(digest string)) *Service_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_GetBlob_Call) Return(reader io.Reader, err error) *Service_GetBlob_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *Service_GetBlob_Call) RunAndReturn(run func(digest string) (io.Reader, error)) *Service_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// GetManifest provides a mock function for the type Service
func (_mock *Service) GetManifest(reference string) (*store.Manifest, []byte, error) {
	ret := _mock.Called(reference)

	if len(ret) == 0 {
		panic("no return value specified for GetManifest")
	}

	var r0 *store.Manifest
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*store.Manifest, []byte, error)); ok {
		return returnFunc(reference)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *store.Manifest); ok {
		r0 = returnFunc(reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Manifest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) []byte); ok {
		r1 = returnFunc(reference)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(reference)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Service_GetManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManifest'
type Service_GetManifest_Call struct {
	*mock.Call
}

// GetManifest is a helper method to define mock.On call
//   - reference string
func (_e *Service_Expecter) GetManifest(reference interface{}) *Service_GetManifest_Call {
	return &Service_GetManifest_Call{Call: _e.mock.On("GetManifest", reference)}
}

func (_c *Service_GetManifest_Call) Run(run func(reference string)) *Service_GetManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_GetManifest_Call) Return(manifest *store.Manifest, bytes []byte, err error) *Service_GetManifest_Call {
	_c.Call.Return(manifest, bytes, err)
	return _c
}

func (_c *Service_GetManifest_Call) RunAndReturn(run func(reference string) (*store.Manifest, []byte, error)) *Service_GetManifest_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function for the type Service
func (_mock *Service) GetTag(tag string) (string, error) {
	ret := _mock.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(tag)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(tag)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type Service_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
//   - tag string
func (_e *Service_Expecter) GetTag(tag interface{}) *Service_GetTag_Call {
	return &Service_GetTag_Call{Call: _e.mock.On("GetTag", tag)}
}

func (_c *Service_GetTag_Call) Run(run func(tag string)) *Service_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_GetTag_Call) Return(s string, err error) *Service_GetTag_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Service_GetTag_Call) RunAndReturn(run func(tag string) (string, error)) *Service_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// InitUpload provides a mock function for the type Service
func (_mock *Service) InitUpload() (*store.UploadSession, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitUpload")
	}

	var r0 *store.UploadSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*store.UploadSession, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *store.UploadSession); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.UploadSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_InitUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitUpload'
type Service_InitUpload_Call struct {
	*mock.Call
}

// InitUpload is a helper method to define mock.On call
func (_e *Service_Expecter) InitUpload() *Service_InitUpload_Call {
	return &Service_InitUpload_Call{Call: _e.mock.On("InitUpload")}
}

func (_c *Service_InitUpload_Call) Run(run func()) *Service_InitUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_InitUpload_Call) Return(uploadSession *store.UploadSession, err error) *Service_InitUpload_Call {
	_c.Call.Return(uploadSession, err)
	return _c
}

func (_c *Service_InitUpload_Call) RunAndReturn(run func() (*store.UploadSession, error)) *Service_InitUpload_Call {
	_c.Call.Return(run)
	return _c
}

// ListReferrers provides a mock function for the type Service
func (_mock *Service) ListReferrers(digest string, opts *repository.ListReferrersOptions) (*repository.Referrers, error) {
	ret := _mock.Called(digest, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListReferrers")
	}

	var r0 *repository.Referrers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *repository.ListReferrersOptions) (*repository.Referrers, error)); ok {
		return returnFunc(digest, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *repository.ListReferrersOptions) *repository.Referrers); ok {
		r0 = returnFunc(digest, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Referrers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *repository.ListReferrersOptions) error); ok {
		r1 = returnFunc(digest, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_ListReferrers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReferrers'
type Service_ListReferrers_Call struct {
	*mock.Call
}

// ListReferrers is a helper method to define mock.On call
//   - digest string
//   - opts *repository.ListReferrersOptions
func (_e *Service_Expecter) ListReferrers(digest interface{}, opts interface{}) *Service_ListReferrers_Call {
	return &Service_ListReferrers_Call{Call: _e.mock.On("ListReferrers", digest, opts)}
}

func (_c *Service_ListReferrers_Call) Run(run func(digest string, opts *repository.ListReferrersOptions)) *Service_ListReferrers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *repository.ListReferrersOptions
		if args[1] != nil {
			arg1 = args[1].(*repository.ListReferrersOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_ListReferrers_Call) Return(referrers *repository.Referrers, err error) *Service_ListReferrers_Call {
	_c.Call.Return(referrers, err)
	return _c
}

func (_c *Service_ListReferrers_Call) RunAndReturn(run func(digest string, opts *repository.ListReferrersOptions) (*repository.Referrers, error)) *Service_ListReferrers_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type Service
func (_mock *Service) ListTags(count int, from string) ([]string, error) {
	ret := _mock.Called(count, from)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) ([]string, error)); ok {
		return returnFunc(count, from)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) []string); ok {
		r0 = returnFunc(count, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(count, from)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type Service_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - count int
//   - from string
func (_e *Service_Expecter) ListTags(count interface{}, from interface{}) *Service_ListTags_Call {
	return &Service_ListTags_Call{Call: _e.mock.On("ListTags", count, from)}
}

func (_c *Service_ListTags_Call) Run(run func(count int, from string)) *Service_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_ListTags_Call) Return(strings []string, err error) *Service_ListTags_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Service_ListTags_Call) RunAndReturn(run func(count int, from string) ([]string, error)) *Service_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// PutManifest provides a mock function for the type Service
func (_mock *Service) PutManifest(reference string, content []byte) (digest.Digest, error) {
	ret := _mock.Called(reference, content)

	if len(ret) == 0 {
		panic("no return value specified for PutManifest")
	}

	var r0 digest.Digest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) (digest.Digest, error)); ok {
		return returnFunc(reference, content)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte) digest.Digest); ok {
		r0 = returnFunc(reference, content)
	} else {
		r0 = ret.Get(0).(digest.Digest)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = returnFunc(reference, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_PutManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutManifest'
type Service_PutManifest_Call struct {
	*mock.Call
}

// PutManifest is a helper method to define mock.On call
//   - reference string
//   - content []byte
func (_e *Service_Expecter) PutManifest(reference interface{}, content interface{}) *Service_PutManifest_Call {
	return &Service_PutManifest_Call{Call: _e.mock.On("PutManifest", reference, content)}
}

func (_c *Service_PutManifest_Call) Run(run func(reference string, content []byte)) *Service_PutManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_PutManifest_Call) Return(digest1 digest.Digest, err error) *Service_PutManifest_Call {
	_c.Call.Return(digest1, err)
	return _c
}

func (_c *Service_PutManifest_Call) RunAndReturn(run func(reference string, content []byte) (digest.Digest, error)) *Service_PutManifest_Call {
	_c.Call.Return(run)
	return _c
}

// PutTag provides a mock function for the type Service
func (_mock *Service) PutTag(tag string, digest1 string) error {
	ret := _mock.Called(tag, digest1)

	if len(ret) == 0 {
		panic("no return value specified for PutTag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(tag, digest1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_PutTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutTag'
type Service_PutTag_Call struct {
	*mock.Call
}

// PutTag is a helper method to define mock.On call
//   - tag string
//   - digest1 string
func (_e *Service_Expecter) PutTag(tag interface{}, digest1 interface{}) *Service_PutTag_Call {
	return &Service_PutTag_Call{Call: _e.mock.On("PutTag", tag, digest1)}
}

func (_c *Service_PutTag_Call) Run(run func(tag string, digest1 string)) *Service_PutTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_PutTag_Call) Return(err error) *Service_PutTag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_PutTag_Call) RunAndReturn(run func(tag string, digest1 string) error) *Service_PutTag_Call {
	_c.Call.Return(run)
	return _c
}

// StatBlob provides a mock function for the type Service
func (_mock *Service) StatBlob(digest1 string) (*store.BlobInfo, error) {
	ret := _mock.Called(digest1)

	if len(ret) == 0 {
		panic("no return value specified for StatBlob")
	}

	var r0 *store.BlobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*store.BlobInfo, error)); ok {
		return returnFunc(digest1)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *store.BlobInfo); ok {
		r0 = returnFunc(digest1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(digest1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_StatBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatBlob'
type Service_StatBlob_Call struct {
	*mock.Call
}

// StatBlob is a helper method to define mock.On call
//   - digest1 string
func (_e *Service_Expecter) StatBlob(digest1 interface{}) *Service_StatBlob_Call {
	return &Service_StatBlob_Call{Call: _e.mock.On("StatBlob", digest1)}
}

func (_c *Service_StatBlob_Call) Run(run func(digest1 string)) *Service_StatBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_StatBlob_Call) Return(blobInfo *store.BlobInfo, err error) *Service_StatBlob_Call {
	_c.Call.Return(blobInfo, err)
	return _c
}

func (_c *Service_StatBlob_Call) RunAndReturn(run func(digest1 string) (*store.BlobInfo, error)) *Service_StatBlob_Call {
	_c.Call.Return(run)
	return _c
}

// StatManifest provides a mock function for the type Service
func (_mock *Service) StatManifest(reference string) (*store.BlobInfo, error) {
	ret := _mock.Called(reference)

	if len(ret) == 0 {
		panic("no return value specified for StatManifest")
	}

	var r0 *store.BlobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*store.BlobInfo, error)); ok {
		return returnFunc(reference)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *store.BlobInfo); ok {
		r0 = returnFunc(reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(reference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_StatManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatManifest'
type Service_StatManifest_Call struct {
	*mock.Call
}

// StatManifest is a helper method to define mock.On call
//   - reference string
func (_e *Service_Expecter) StatManifest(reference interface{}) *Service_StatManifest_Call {
	return &Service_StatManifest_Call{Call: _e.mock.On("StatManifest", reference)}
}

func (_c *Service_StatManifest_Call) Run(run func(reference string)) *Service_StatManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_StatManifest_Call) Return(blobInfo *store.BlobInfo, err error) *Service_StatManifest_Call {
	_c.Call.Return(blobInfo, err)
	return _c
}

func (_c *Service_StatManifest_Call) RunAndReturn(run func(reference string) (*store.BlobInfo, error)) *Service_StatManifest_Call {
	_c.Call.Return(run)
	return _c
}

// StatUpload provides a mock function for the type Service
func (_mock *Service) StatUpload(sessionID string) (*store.BlobInfo, error) {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for StatUpload")
	}

	var r0 *store.BlobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*store.BlobInfo, error)); ok {
		return returnFunc(sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *store.BlobInfo); ok {
		r0 = returnFunc(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_StatUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatUpload'
type Service_StatUpload_Call struct {
	*mock.Call
}

// StatUpload is a helper method to define mock.On call
//   - sessionID string
func (_e *Service_Expecter) StatUpload(sessionID interface{}) *Service_StatUpload_Call {
	return &Service_StatUpload_Call{Call: _e.mock.On("StatUpload", sessionID)}
}

func (_c *Service_StatUpload_Call) Run(run func(sessionID string)) *Service_StatUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_StatUpload_Call) Return(blobInfo *store.BlobInfo, err error) *Service_StatUpload_Call {
	_c.Call.Return(blobInfo, err)
	return _c
}

func (_c *Service_StatUpload_Call) RunAndReturn(run func(sessionID string) (*store.BlobInfo, error)) *Service_StatUpload_Call {
	_c.Call.Return(run)
	return _c
}
