// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"net/http"

	"github.com/robinkb/cascade/cluster"
	"github.com/robinkb/cascade/cluster/raft"
	mock "github.com/stretchr/testify/mock"
	raft0 "go.etcd.io/raft/v3"
	"go.etcd.io/raft/v3/raftpb"
)

// NewNode creates a new instance of Node. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *Node {
	mock := &Node{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Node is an autogenerated mock type for the Node type
type Node struct {
	mock.Mock
}

type Node_Expecter struct {
	mock *mock.Mock
}

func (_m *Node) EXPECT() *Node_Expecter {
	return &Node_Expecter{mock: &_m.Mock}
}

// AddPeer provides a mock function for the type Node
func (_mock *Node) AddPeer(peer cluster.Peer) error {
	ret := _mock.Called(peer)

	if len(ret) == 0 {
		panic("no return value specified for AddPeer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(cluster.Peer) error); ok {
		r0 = returnFunc(peer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_AddPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPeer'
type Node_AddPeer_Call struct {
	*mock.Call
}

// AddPeer is a helper method to define mock.On call
//   - peer cluster.Peer
func (_e *Node_Expecter) AddPeer(peer interface{}) *Node_AddPeer_Call {
	return &Node_AddPeer_Call{Call: _e.mock.On("AddPeer", peer)}
}

func (_c *Node_AddPeer_Call) Run(run func(peer cluster.Peer)) *Node_AddPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cluster.Peer
		if args[0] != nil {
			arg0 = args[0].(cluster.Peer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Node_AddPeer_Call) Return(err error) *Node_AddPeer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_AddPeer_Call) RunAndReturn(run func(peer cluster.Peer) error) *Node_AddPeer_Call {
	_c.Call.Return(run)
	return _c
}

// AsPeer provides a mock function for the type Node
func (_mock *Node) AsPeer() cluster.Peer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AsPeer")
	}

	var r0 cluster.Peer
	if returnFunc, ok := ret.Get(0).(func() cluster.Peer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(cluster.Peer)
	}
	return r0
}

// Node_AsPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsPeer'
type Node_AsPeer_Call struct {
	*mock.Call
}

// AsPeer is a helper method to define mock.On call
func (_e *Node_Expecter) AsPeer() *Node_AsPeer_Call {
	return &Node_AsPeer_Call{Call: _e.mock.On("AsPeer")}
}

func (_c *Node_AsPeer_Call) Run(run func()) *Node_AsPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_AsPeer_Call) Return(peer cluster.Peer) *Node_AsPeer_Call {
	_c.Call.Return(peer)
	return _c
}

func (_c *Node_AsPeer_Call) RunAndReturn(run func() cluster.Peer) *Node_AsPeer_Call {
	_c.Call.Return(run)
	return _c
}

// Bootstrap provides a mock function for the type Node
func (_mock *Node) Bootstrap(peers ...cluster.Peer) {
	if len(peers) > 0 {
		_mock.Called(peers)
	} else {
		_mock.Called()
	}

	return
}

// Node_Bootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bootstrap'
type Node_Bootstrap_Call struct {
	*mock.Call
}

// Bootstrap is a helper method to define mock.On call
//   - peers ...cluster.Peer
func (_e *Node_Expecter) Bootstrap(peers ...interface{}) *Node_Bootstrap_Call {
	return &Node_Bootstrap_Call{Call: _e.mock.On("Bootstrap",
		append([]interface{}{}, peers...)...)}
}

func (_c *Node_Bootstrap_Call) Run(run func(peers ...cluster.Peer)) *Node_Bootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []cluster.Peer
		var variadicArgs []cluster.Peer
		if len(args) > 0 {
			variadicArgs = args[0].([]cluster.Peer)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Node_Bootstrap_Call) Return() *Node_Bootstrap_Call {
	_c.Call.Return()
	return _c
}

func (_c *Node_Bootstrap_Call) RunAndReturn(run func(peers ...cluster.Peer)) *Node_Bootstrap_Call {
	_c.Run(run)
	return _c
}

// Emit provides a mock function for the type Node
func (_mock *Node) Emit(ctx context.Context, receiver string) <-chan raft.Event {
	ret := _mock.Called(ctx, receiver)

	if len(ret) == 0 {
		panic("no return value specified for Emit")
	}

	var r0 <-chan raft.Event
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) <-chan raft.Event); ok {
		r0 = returnFunc(ctx, receiver)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan raft.Event)
		}
	}
	return r0
}

// Node_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type Node_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - receiver string
func (_e *Node_Expecter) Emit(ctx interface{}, receiver interface{}) *Node_Emit_Call {
	return &Node_Emit_Call{Call: _e.mock.On("Emit", ctx, receiver)}
}

func (_c *Node_Emit_Call) Run(run func(ctx context.Context, receiver string)) *Node_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Node_Emit_Call) Return(eventCh <-chan raft.Event) *Node_Emit_Call {
	_c.Call.Return(eventCh)
	return _c
}

func (_c *Node_Emit_Call) RunAndReturn(run func(ctx context.Context, receiver string) <-chan raft.Event) *Node_Emit_Call {
	_c.Call.Return(run)
	return _c
}

// Handle provides a mock function for the type Node
func (_mock *Node) Handle(t cluster.ProposalType, f cluster.ProposalFunc) {
	_mock.Called(t, f)
	return
}

// Node_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Node_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - t cluster.ProposalType
//   - f cluster.ProposalFunc
func (_e *Node_Expecter) Handle(t interface{}, f interface{}) *Node_Handle_Call {
	return &Node_Handle_Call{Call: _e.mock.On("Handle", t, f)}
}

func (_c *Node_Handle_Call) Run(run func(t cluster.ProposalType, f cluster.ProposalFunc)) *Node_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cluster.ProposalType
		if args[0] != nil {
			arg0 = args[0].(cluster.ProposalType)
		}
		var arg1 cluster.ProposalFunc
		if args[1] != nil {
			arg1 = args[1].(cluster.ProposalFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Node_Handle_Call) Return() *Node_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *Node_Handle_Call) RunAndReturn(run func(t cluster.ProposalType, f cluster.ProposalFunc)) *Node_Handle_Call {
	_c.Run(run)
	return _c
}

// Handler provides a mock function for the type Node
func (_mock *Node) Handler() http.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func() http.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// Node_Handler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handler'
type Node_Handler_Call struct {
	*mock.Call
}

// Handler is a helper method to define mock.On call
func (_e *Node_Expecter) Handler() *Node_Handler_Call {
	return &Node_Handler_Call{Call: _e.mock.On("Handler")}
}

func (_c *Node_Handler_Call) Run(run func()) *Node_Handler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Handler_Call) Return(handler http.Handler) *Node_Handler_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *Node_Handler_Call) RunAndReturn(run func() http.Handler) *Node_Handler_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type Node
func (_mock *Node) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Node_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Node_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Node_Expecter) Name() *Node_Name_Call {
	return &Node_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Node_Name_Call) Run(run func()) *Node_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Name_Call) Return(s string) *Node_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Node_Name_Call) RunAndReturn(run func() string) *Node_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Propose provides a mock function for the type Node
func (_mock *Node) Propose(t cluster.ProposalType, data []byte) (any, error) {
	ret := _mock.Called(t, data)

	if len(ret) == 0 {
		panic("no return value specified for Propose")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(cluster.ProposalType, []byte) (any, error)); ok {
		return returnFunc(t, data)
	}
	if returnFunc, ok := ret.Get(0).(func(cluster.ProposalType, []byte) any); ok {
		r0 = returnFunc(t, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(cluster.ProposalType, []byte) error); ok {
		r1 = returnFunc(t, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Node_Propose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Propose'
type Node_Propose_Call struct {
	*mock.Call
}

// Propose is a helper method to define mock.On call
//   - t cluster.ProposalType
//   - data []byte
func (_e *Node_Expecter) Propose(t interface{}, data interface{}) *Node_Propose_Call {
	return &Node_Propose_Call{Call: _e.mock.On("Propose", t, data)}
}

func (_c *Node_Propose_Call) Run(run func(t cluster.ProposalType, data []byte)) *Node_Propose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cluster.ProposalType
		if args[0] != nil {
			arg0 = args[0].(cluster.ProposalType)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Node_Propose_Call) Return(resp any, err error) *Node_Propose_Call {
	_c.Call.Return(resp, err)
	return _c
}

func (_c *Node_Propose_Call) RunAndReturn(run func(t cluster.ProposalType, data []byte) (any, error)) *Node_Propose_Call {
	_c.Call.Return(run)
	return _c
}

// ReadState provides a mock function for the type Node
func (_mock *Node) ReadState() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_ReadState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadState'
type Node_ReadState_Call struct {
	*mock.Call
}

// ReadState is a helper method to define mock.On call
func (_e *Node_Expecter) ReadState() *Node_ReadState_Call {
	return &Node_ReadState_Call{Call: _e.mock.On("ReadState")}
}

func (_c *Node_ReadState_Call) Run(run func()) *Node_ReadState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_ReadState_Call) Return(err error) *Node_ReadState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_ReadState_Call) RunAndReturn(run func() error) *Node_ReadState_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type Node
func (_mock *Node) Receive(m *raftpb.Message) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*raftpb.Message) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type Node_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - m *raftpb.Message
func (_e *Node_Expecter) Receive(m interface{}) *Node_Receive_Call {
	return &Node_Receive_Call{Call: _e.mock.On("Receive", m)}
}

func (_c *Node_Receive_Call) Run(run func(m *raftpb.Message)) *Node_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *raftpb.Message
		if args[0] != nil {
			arg0 = args[0].(*raftpb.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Node_Receive_Call) Return(err error) *Node_Receive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_Receive_Call) RunAndReturn(run func(m *raftpb.Message) error) *Node_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePeer provides a mock function for the type Node
func (_mock *Node) RemovePeer(peer cluster.Peer) error {
	ret := _mock.Called(peer)

	if len(ret) == 0 {
		panic("no return value specified for RemovePeer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(cluster.Peer) error); ok {
		r0 = returnFunc(peer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_RemovePeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePeer'
type Node_RemovePeer_Call struct {
	*mock.Call
}

// RemovePeer is a helper method to define mock.On call
//   - peer cluster.Peer
func (_e *Node_Expecter) RemovePeer(peer interface{}) *Node_RemovePeer_Call {
	return &Node_RemovePeer_Call{Call: _e.mock.On("RemovePeer", peer)}
}

func (_c *Node_RemovePeer_Call) Run(run func(peer cluster.Peer)) *Node_RemovePeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cluster.Peer
		if args[0] != nil {
			arg0 = args[0].(cluster.Peer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Node_RemovePeer_Call) Return(err error) *Node_RemovePeer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_RemovePeer_Call) RunAndReturn(run func(peer cluster.Peer) error) *Node_RemovePeer_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type Node
func (_mock *Node) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Node_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *Node_Expecter) Run() *Node_Run_Call {
	return &Node_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *Node_Run_Call) Run(run func()) *Node_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Run_Call) Return(err error) *Node_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_Run_Call) RunAndReturn(run func() error) *Node_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type Node
func (_mock *Node) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Node_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type Node_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *Node_Expecter) Shutdown() *Node_Shutdown_Call {
	return &Node_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *Node_Shutdown_Call) Run(run func()) *Node_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Shutdown_Call) Return(err error) *Node_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Node_Shutdown_Call) RunAndReturn(run func() error) *Node_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type Node
func (_mock *Node) Status() raft0.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 raft0.Status
	if returnFunc, ok := ret.Get(0).(func() raft0.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(raft0.Status)
	}
	return r0
}

// Node_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type Node_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *Node_Expecter) Status() *Node_Status_Call {
	return &Node_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *Node_Status_Call) Run(run func()) *Node_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Status_Call) Return(status raft0.Status) *Node_Status_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *Node_Status_Call) RunAndReturn(run func() raft0.Status) *Node_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Tick provides a mock function for the type Node
func (_mock *Node) Tick() {
	_mock.Called()
	return
}

// Node_Tick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tick'
type Node_Tick_Call struct {
	*mock.Call
}

// Tick is a helper method to define mock.On call
func (_e *Node_Expecter) Tick() *Node_Tick_Call {
	return &Node_Tick_Call{Call: _e.mock.On("Tick")}
}

func (_c *Node_Tick_Call) Run(run func()) *Node_Tick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Node_Tick_Call) Return() *Node_Tick_Call {
	_c.Call.Return()
	return _c
}

func (_c *Node_Tick_Call) RunAndReturn(run func()) *Node_Tick_Call {
	_c.Run(run)
	return _c
}
