// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: metadata.proto

package storepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Manifest represents the metadata of a manifest that is stored in the MetadataStore.
type Manifest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Annotations  map[string]string      `protobuf:"bytes,1,rep,name=annotations" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ArtifactType *string                `protobuf:"bytes,2,opt,name=artifact_type,json=artifactType"`
	xxx_hidden_MediaType    *string                `protobuf:"bytes,3,opt,name=media_type,json=mediaType"`
	xxx_hidden_Size         int64                  `protobuf:"varint,4,opt,name=size"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Manifest) GetAnnotations() map[string]string {
	if x != nil {
		return x.xxx_hidden_Annotations
	}
	return nil
}

func (x *Manifest) GetArtifactType() string {
	if x != nil {
		if x.xxx_hidden_ArtifactType != nil {
			return *x.xxx_hidden_ArtifactType
		}
		return ""
	}
	return ""
}

func (x *Manifest) GetMediaType() string {
	if x != nil {
		if x.xxx_hidden_MediaType != nil {
			return *x.xxx_hidden_MediaType
		}
		return ""
	}
	return ""
}

func (x *Manifest) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *Manifest) SetAnnotations(v map[string]string) {
	x.xxx_hidden_Annotations = v
}

func (x *Manifest) SetArtifactType(v string) {
	x.xxx_hidden_ArtifactType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Manifest) SetMediaType(v string) {
	x.xxx_hidden_MediaType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Manifest) SetSize(v int64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Manifest) HasArtifactType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Manifest) HasMediaType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Manifest) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Manifest) ClearArtifactType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ArtifactType = nil
}

func (x *Manifest) ClearMediaType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_MediaType = nil
}

func (x *Manifest) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Size = 0
}

type Manifest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Annotations  map[string]string
	ArtifactType *string
	MediaType    *string
	Size         *int64
}

func (b0 Manifest_builder) Build() *Manifest {
	m0 := &Manifest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Annotations = b.Annotations
	if b.ArtifactType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ArtifactType = b.ArtifactType
	}
	if b.MediaType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_MediaType = b.MediaType
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Size = *b.Size
	}
	return m0
}

// References defines the various ways in which a manifest can point to other objects in the registry.
// These are mostly used to establish links between objects for garbage collection.
type References struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Config      *string                `protobuf:"bytes,1,opt,name=config"`
	xxx_hidden_Layers      []string               `protobuf:"bytes,2,rep,name=layers"`
	xxx_hidden_Manifests   []string               `protobuf:"bytes,3,rep,name=manifests"`
	xxx_hidden_Subject     *string                `protobuf:"bytes,4,opt,name=subject"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *References) Reset() {
	*x = References{}
	mi := &file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *References) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*References) ProtoMessage() {}

func (x *References) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *References) GetConfig() string {
	if x != nil {
		if x.xxx_hidden_Config != nil {
			return *x.xxx_hidden_Config
		}
		return ""
	}
	return ""
}

func (x *References) GetLayers() []string {
	if x != nil {
		return x.xxx_hidden_Layers
	}
	return nil
}

func (x *References) GetManifests() []string {
	if x != nil {
		return x.xxx_hidden_Manifests
	}
	return nil
}

func (x *References) GetSubject() string {
	if x != nil {
		if x.xxx_hidden_Subject != nil {
			return *x.xxx_hidden_Subject
		}
		return ""
	}
	return ""
}

func (x *References) SetConfig(v string) {
	x.xxx_hidden_Config = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *References) SetLayers(v []string) {
	x.xxx_hidden_Layers = v
}

func (x *References) SetManifests(v []string) {
	x.xxx_hidden_Manifests = v
}

func (x *References) SetSubject(v string) {
	x.xxx_hidden_Subject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *References) HasConfig() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *References) HasSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *References) ClearConfig() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Config = nil
}

func (x *References) ClearSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Subject = nil
}

type References_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Config references a configuration object for a container like in an OCI Image Manifest.
	// It is used for tracking links from image manifests to a blob for garbage collection.
	Config *string
	// Layers is a slice of digests pointing to blobs like in an OCI Image Manifest.
	// It is used for tracking links from image manifests to blobs for garbage collection.
	Layers []string
	// Manifests is a slice of digests pointing to other manifests like in an OCI Image Index.
	// It is used for tracking links from image index manifests to other manifests for garbage collection.
	Manifests []string
	// Subject is a digest pointing to another manifest as used by the Referrers API.
	// Besides being used for the Referrers API, it is also used for garbage collection.
	Subject *string
}

func (b0 References_builder) Build() *References {
	m0 := &References{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Config != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Config = b.Config
	}
	x.xxx_hidden_Layers = b.Layers
	x.xxx_hidden_Manifests = b.Manifests
	if b.Subject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Subject = b.Subject
	}
	return m0
}

type UploadSession struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_StartDate   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate"`
	xxx_hidden_HashState   []byte                 `protobuf:"bytes,3,opt,name=hash_state,json=hashState"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UploadSession) Reset() {
	*x = UploadSession{}
	mi := &file_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSession) ProtoMessage() {}

func (x *UploadSession) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadSession) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *UploadSession) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_StartDate
	}
	return nil
}

func (x *UploadSession) GetHashState() []byte {
	if x != nil {
		return x.xxx_hidden_HashState
	}
	return nil
}

func (x *UploadSession) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *UploadSession) SetStartDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_StartDate = v
}

func (x *UploadSession) SetHashState(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_HashState = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *UploadSession) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UploadSession) HasStartDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StartDate != nil
}

func (x *UploadSession) HasHashState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UploadSession) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UploadSession) ClearStartDate() {
	x.xxx_hidden_StartDate = nil
}

func (x *UploadSession) ClearHashState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_HashState = nil
}

type UploadSession_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        []byte
	StartDate *timestamppb.Timestamp
	HashState []byte
}

func (b0 UploadSession_builder) Build() *UploadSession {
	m0 := &UploadSession{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_StartDate = b.StartDate
	if b.HashState != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_HashState = b.HashState
	}
	return m0
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\x12\astorepb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\bManifest\x12D\n" +
	"\vannotations\x18\x01 \x03(\v2\".storepb.Manifest.AnnotationsEntryR\vannotations\x12#\n" +
	"\rartifact_type\x18\x02 \x01(\tR\fartifactType\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\n" +
	"References\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12\x16\n" +
	"\x06layers\x18\x02 \x03(\tR\x06layers\x12\x1c\n" +
	"\tmanifests\x18\x03 \x03(\tR\tmanifests\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\"y\n" +
	"\rUploadSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x12\x1d\n" +
	"\n" +
	"hash_state\x18\x03 \x01(\fR\thashStateB\x18Z\x16registry/store/storepbb\beditionsp\xe9\a"

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_metadata_proto_goTypes = []any{
	(*Manifest)(nil),              // 0: storepb.Manifest
	(*References)(nil),            // 1: storepb.References
	(*UploadSession)(nil),         // 2: storepb.UploadSession
	nil,                           // 3: storepb.Manifest.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_metadata_proto_depIdxs = []int32{
	3, // 0: storepb.Manifest.annotations:type_name -> storepb.Manifest.AnnotationsEntry
	4, // 1: storepb.UploadSession.start_date:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
