// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/robinkb/cascade-registry/cluster"
	mock "github.com/stretchr/testify/mock"
	"go.etcd.io/raft/v3/raftpb"
)

// NewRaftNode creates a new instance of RaftNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRaftNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *RaftNode {
	mock := &RaftNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RaftNode is an autogenerated mock type for the Node type
type RaftNode struct {
	mock.Mock
}

type RaftNode_Expecter struct {
	mock *mock.Mock
}

func (_m *RaftNode) EXPECT() *RaftNode_Expecter {
	return &RaftNode_Expecter{mock: &_m.Mock}
}

// ClusterStatus provides a mock function for the type RaftNode
func (_mock *RaftNode) ClusterStatus() cluster.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClusterStatus")
	}

	var r0 cluster.Status
	if returnFunc, ok := ret.Get(0).(func() cluster.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(cluster.Status)
	}
	return r0
}

// RaftNode_ClusterStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterStatus'
type RaftNode_ClusterStatus_Call struct {
	*mock.Call
}

// ClusterStatus is a helper method to define mock.On call
func (_e *RaftNode_Expecter) ClusterStatus() *RaftNode_ClusterStatus_Call {
	return &RaftNode_ClusterStatus_Call{Call: _e.mock.On("ClusterStatus")}
}

func (_c *RaftNode_ClusterStatus_Call) Run(run func()) *RaftNode_ClusterStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_ClusterStatus_Call) Return(status cluster.Status) *RaftNode_ClusterStatus_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *RaftNode_ClusterStatus_Call) RunAndReturn(run func() cluster.Status) *RaftNode_ClusterStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type RaftNode
func (_mock *RaftNode) Receive(m *raftpb.Message) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*raftpb.Message) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RaftNode_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type RaftNode_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - m
func (_e *RaftNode_Expecter) Receive(m interface{}) *RaftNode_Receive_Call {
	return &RaftNode_Receive_Call{Call: _e.mock.On("Receive", m)}
}

func (_c *RaftNode_Receive_Call) Run(run func(m *raftpb.Message)) *RaftNode_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*raftpb.Message))
	})
	return _c
}

func (_c *RaftNode_Receive_Call) Return(err error) *RaftNode_Receive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RaftNode_Receive_Call) RunAndReturn(run func(m *raftpb.Message) error) *RaftNode_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type RaftNode
func (_mock *RaftNode) Start() {
	_mock.Called()
	return
}

// RaftNode_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type RaftNode_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *RaftNode_Expecter) Start() *RaftNode_Start_Call {
	return &RaftNode_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *RaftNode_Start_Call) Run(run func()) *RaftNode_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_Start_Call) Return() *RaftNode_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Start_Call) RunAndReturn(run func()) *RaftNode_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type RaftNode
func (_mock *RaftNode) Stop() {
	_mock.Called()
	return
}

// RaftNode_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type RaftNode_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *RaftNode_Expecter) Stop() *RaftNode_Stop_Call {
	return &RaftNode_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *RaftNode_Stop_Call) Run(run func()) *RaftNode_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_Stop_Call) Return() *RaftNode_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Stop_Call) RunAndReturn(run func()) *RaftNode_Stop_Call {
	_c.Run(run)
	return _c
}

// Tick provides a mock function for the type RaftNode
func (_mock *RaftNode) Tick() {
	_mock.Called()
	return
}

// RaftNode_Tick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tick'
type RaftNode_Tick_Call struct {
	*mock.Call
}

// Tick is a helper method to define mock.On call
func (_e *RaftNode_Expecter) Tick() *RaftNode_Tick_Call {
	return &RaftNode_Tick_Call{Call: _e.mock.On("Tick")}
}

func (_c *RaftNode_Tick_Call) Run(run func()) *RaftNode_Tick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_Tick_Call) Return() *RaftNode_Tick_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Tick_Call) RunAndReturn(run func()) *RaftNode_Tick_Call {
	_c.Run(run)
	return _c
}
