// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
	"go.etcd.io/raft/v3/raftpb"
)

// NewRaftReceiver creates a new instance of RaftReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRaftReceiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *RaftReceiver {
	mock := &RaftReceiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RaftReceiver is an autogenerated mock type for the Receiver type
type RaftReceiver struct {
	mock.Mock
}

type RaftReceiver_Expecter struct {
	mock *mock.Mock
}

func (_m *RaftReceiver) EXPECT() *RaftReceiver_Expecter {
	return &RaftReceiver_Expecter{mock: &_m.Mock}
}

// Receive provides a mock function for the type RaftReceiver
func (_mock *RaftReceiver) Receive(msg *raftpb.Message) error {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*raftpb.Message) error); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RaftReceiver_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type RaftReceiver_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - msg
func (_e *RaftReceiver_Expecter) Receive(msg interface{}) *RaftReceiver_Receive_Call {
	return &RaftReceiver_Receive_Call{Call: _e.mock.On("Receive", msg)}
}

func (_c *RaftReceiver_Receive_Call) Run(run func(msg *raftpb.Message)) *RaftReceiver_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*raftpb.Message))
	})
	return _c
}

func (_c *RaftReceiver_Receive_Call) Return(err error) *RaftReceiver_Receive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RaftReceiver_Receive_Call) RunAndReturn(run func(msg *raftpb.Message) error) *RaftReceiver_Receive_Call {
	_c.Call.Return(run)
	return _c
}
