// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"
	"net/netip"

	"github.com/robinkb/cascade/cluster"
	"github.com/robinkb/cascade/cluster/raft"
	mock "github.com/stretchr/testify/mock"
	raft0 "go.etcd.io/raft/v3"
	"go.etcd.io/raft/v3/raftpb"
)

// NewRaftNode creates a new instance of RaftNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRaftNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *RaftNode {
	mock := &RaftNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RaftNode is an autogenerated mock type for the Node type
type RaftNode struct {
	mock.Mock
}

type RaftNode_Expecter struct {
	mock *mock.Mock
}

func (_m *RaftNode) EXPECT() *RaftNode_Expecter {
	return &RaftNode_Expecter{mock: &_m.Mock}
}

// AddNode provides a mock function for the type RaftNode
func (_mock *RaftNode) AddNode(ctx context.Context, peer raft.Peer) error {
	ret := _mock.Called(ctx, peer)

	if len(ret) == 0 {
		panic("no return value specified for AddNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, raft.Peer) error); ok {
		r0 = returnFunc(ctx, peer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RaftNode_AddNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNode'
type RaftNode_AddNode_Call struct {
	*mock.Call
}

// AddNode is a helper method to define mock.On call
//   - ctx context.Context
//   - peer raft.Peer
func (_e *RaftNode_Expecter) AddNode(ctx interface{}, peer interface{}) *RaftNode_AddNode_Call {
	return &RaftNode_AddNode_Call{Call: _e.mock.On("AddNode", ctx, peer)}
}

func (_c *RaftNode_AddNode_Call) Run(run func(ctx context.Context, peer raft.Peer)) *RaftNode_AddNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 raft.Peer
		if args[1] != nil {
			arg1 = args[1].(raft.Peer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RaftNode_AddNode_Call) Return(err error) *RaftNode_AddNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RaftNode_AddNode_Call) RunAndReturn(run func(ctx context.Context, peer raft.Peer) error) *RaftNode_AddNode_Call {
	_c.Call.Return(run)
	return _c
}

// AddrPort provides a mock function for the type RaftNode
func (_mock *RaftNode) AddrPort() netip.AddrPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddrPort")
	}

	var r0 netip.AddrPort
	if returnFunc, ok := ret.Get(0).(func() netip.AddrPort); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(netip.AddrPort)
	}
	return r0
}

// RaftNode_AddrPort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddrPort'
type RaftNode_AddrPort_Call struct {
	*mock.Call
}

// AddrPort is a helper method to define mock.On call
func (_e *RaftNode_Expecter) AddrPort() *RaftNode_AddrPort_Call {
	return &RaftNode_AddrPort_Call{Call: _e.mock.On("AddrPort")}
}

func (_c *RaftNode_AddrPort_Call) Run(run func()) *RaftNode_AddrPort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_AddrPort_Call) Return(addrPort netip.AddrPort) *RaftNode_AddrPort_Call {
	_c.Call.Return(addrPort)
	return _c
}

func (_c *RaftNode_AddrPort_Call) RunAndReturn(run func() netip.AddrPort) *RaftNode_AddrPort_Call {
	_c.Call.Return(run)
	return _c
}

// AsPeer provides a mock function for the type RaftNode
func (_mock *RaftNode) AsPeer() raft.Peer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AsPeer")
	}

	var r0 raft.Peer
	if returnFunc, ok := ret.Get(0).(func() raft.Peer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(raft.Peer)
	}
	return r0
}

// RaftNode_AsPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsPeer'
type RaftNode_AsPeer_Call struct {
	*mock.Call
}

// AsPeer is a helper method to define mock.On call
func (_e *RaftNode_Expecter) AsPeer() *RaftNode_AsPeer_Call {
	return &RaftNode_AsPeer_Call{Call: _e.mock.On("AsPeer")}
}

func (_c *RaftNode_AsPeer_Call) Run(run func()) *RaftNode_AsPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_AsPeer_Call) Return(peer raft.Peer) *RaftNode_AsPeer_Call {
	_c.Call.Return(peer)
	return _c
}

func (_c *RaftNode_AsPeer_Call) RunAndReturn(run func() raft.Peer) *RaftNode_AsPeer_Call {
	_c.Call.Return(run)
	return _c
}

// Bootstrap provides a mock function for the type RaftNode
func (_mock *RaftNode) Bootstrap(peers ...raft.Peer) {
	if len(peers) > 0 {
		_mock.Called(peers)
	} else {
		_mock.Called()
	}

	return
}

// RaftNode_Bootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bootstrap'
type RaftNode_Bootstrap_Call struct {
	*mock.Call
}

// Bootstrap is a helper method to define mock.On call
//   - peers ...raft.Peer
func (_e *RaftNode_Expecter) Bootstrap(peers ...interface{}) *RaftNode_Bootstrap_Call {
	return &RaftNode_Bootstrap_Call{Call: _e.mock.On("Bootstrap",
		append([]interface{}{}, peers...)...)}
}

func (_c *RaftNode_Bootstrap_Call) Run(run func(peers ...raft.Peer)) *RaftNode_Bootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []raft.Peer
		var variadicArgs []raft.Peer
		if len(args) > 0 {
			variadicArgs = args[0].([]raft.Peer)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *RaftNode_Bootstrap_Call) Return() *RaftNode_Bootstrap_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Bootstrap_Call) RunAndReturn(run func(peers ...raft.Peer)) *RaftNode_Bootstrap_Call {
	_c.Run(run)
	return _c
}

// Handle provides a mock function for the type RaftNode
func (_mock *RaftNode) Handle(p cluster.Proposal, f cluster.HandlerFunc) {
	_mock.Called(p, f)
	return
}

// RaftNode_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type RaftNode_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - p cluster.Proposal
//   - f cluster.HandlerFunc
func (_e *RaftNode_Expecter) Handle(p interface{}, f interface{}) *RaftNode_Handle_Call {
	return &RaftNode_Handle_Call{Call: _e.mock.On("Handle", p, f)}
}

func (_c *RaftNode_Handle_Call) Run(run func(p cluster.Proposal, f cluster.HandlerFunc)) *RaftNode_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cluster.Proposal
		if args[0] != nil {
			arg0 = args[0].(cluster.Proposal)
		}
		var arg1 cluster.HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(cluster.HandlerFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RaftNode_Handle_Call) Return() *RaftNode_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Handle_Call) RunAndReturn(run func(p cluster.Proposal, f cluster.HandlerFunc)) *RaftNode_Handle_Call {
	_c.Run(run)
	return _c
}

// NodeID provides a mock function for the type RaftNode
func (_mock *RaftNode) NodeID() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeID")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// RaftNode_NodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeID'
type RaftNode_NodeID_Call struct {
	*mock.Call
}

// NodeID is a helper method to define mock.On call
func (_e *RaftNode_Expecter) NodeID() *RaftNode_NodeID_Call {
	return &RaftNode_NodeID_Call{Call: _e.mock.On("NodeID")}
}

func (_c *RaftNode_NodeID_Call) Run(run func()) *RaftNode_NodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_NodeID_Call) Return(v uint64) *RaftNode_NodeID_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *RaftNode_NodeID_Call) RunAndReturn(run func() uint64) *RaftNode_NodeID_Call {
	_c.Call.Return(run)
	return _c
}

// Propose provides a mock function for the type RaftNode
func (_mock *RaftNode) Propose(p cluster.Proposal) error {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Propose")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(cluster.Proposal) error); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RaftNode_Propose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Propose'
type RaftNode_Propose_Call struct {
	*mock.Call
}

// Propose is a helper method to define mock.On call
//   - p cluster.Proposal
func (_e *RaftNode_Expecter) Propose(p interface{}) *RaftNode_Propose_Call {
	return &RaftNode_Propose_Call{Call: _e.mock.On("Propose", p)}
}

func (_c *RaftNode_Propose_Call) Run(run func(p cluster.Proposal)) *RaftNode_Propose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cluster.Proposal
		if args[0] != nil {
			arg0 = args[0].(cluster.Proposal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RaftNode_Propose_Call) Return(err error) *RaftNode_Propose_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RaftNode_Propose_Call) RunAndReturn(run func(p cluster.Proposal) error) *RaftNode_Propose_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type RaftNode
func (_mock *RaftNode) Receive(m *raftpb.Message) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*raftpb.Message) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RaftNode_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type RaftNode_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - m *raftpb.Message
func (_e *RaftNode_Expecter) Receive(m interface{}) *RaftNode_Receive_Call {
	return &RaftNode_Receive_Call{Call: _e.mock.On("Receive", m)}
}

func (_c *RaftNode_Receive_Call) Run(run func(m *raftpb.Message)) *RaftNode_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *raftpb.Message
		if args[0] != nil {
			arg0 = args[0].(*raftpb.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RaftNode_Receive_Call) Return(err error) *RaftNode_Receive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RaftNode_Receive_Call) RunAndReturn(run func(m *raftpb.Message) error) *RaftNode_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNode provides a mock function for the type RaftNode
func (_mock *RaftNode) RemoveNode(ctx context.Context, peer raft.Peer) error {
	ret := _mock.Called(ctx, peer)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, raft.Peer) error); ok {
		r0 = returnFunc(ctx, peer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RaftNode_RemoveNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNode'
type RaftNode_RemoveNode_Call struct {
	*mock.Call
}

// RemoveNode is a helper method to define mock.On call
//   - ctx context.Context
//   - peer raft.Peer
func (_e *RaftNode_Expecter) RemoveNode(ctx interface{}, peer interface{}) *RaftNode_RemoveNode_Call {
	return &RaftNode_RemoveNode_Call{Call: _e.mock.On("RemoveNode", ctx, peer)}
}

func (_c *RaftNode_RemoveNode_Call) Run(run func(ctx context.Context, peer raft.Peer)) *RaftNode_RemoveNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 raft.Peer
		if args[1] != nil {
			arg1 = args[1].(raft.Peer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RaftNode_RemoveNode_Call) Return(err error) *RaftNode_RemoveNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RaftNode_RemoveNode_Call) RunAndReturn(run func(ctx context.Context, peer raft.Peer) error) *RaftNode_RemoveNode_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type RaftNode
func (_mock *RaftNode) Start() {
	_mock.Called()
	return
}

// RaftNode_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type RaftNode_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *RaftNode_Expecter) Start() *RaftNode_Start_Call {
	return &RaftNode_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *RaftNode_Start_Call) Run(run func()) *RaftNode_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_Start_Call) Return() *RaftNode_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Start_Call) RunAndReturn(run func()) *RaftNode_Start_Call {
	_c.Run(run)
	return _c
}

// Status provides a mock function for the type RaftNode
func (_mock *RaftNode) Status() raft0.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 raft0.Status
	if returnFunc, ok := ret.Get(0).(func() raft0.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(raft0.Status)
	}
	return r0
}

// RaftNode_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type RaftNode_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *RaftNode_Expecter) Status() *RaftNode_Status_Call {
	return &RaftNode_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *RaftNode_Status_Call) Run(run func()) *RaftNode_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_Status_Call) Return(status raft0.Status) *RaftNode_Status_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *RaftNode_Status_Call) RunAndReturn(run func() raft0.Status) *RaftNode_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type RaftNode
func (_mock *RaftNode) Stop() {
	_mock.Called()
	return
}

// RaftNode_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type RaftNode_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *RaftNode_Expecter) Stop() *RaftNode_Stop_Call {
	return &RaftNode_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *RaftNode_Stop_Call) Run(run func()) *RaftNode_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_Stop_Call) Return() *RaftNode_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Stop_Call) RunAndReturn(run func()) *RaftNode_Stop_Call {
	_c.Run(run)
	return _c
}

// Tick provides a mock function for the type RaftNode
func (_mock *RaftNode) Tick() {
	_mock.Called()
	return
}

// RaftNode_Tick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tick'
type RaftNode_Tick_Call struct {
	*mock.Call
}

// Tick is a helper method to define mock.On call
func (_e *RaftNode_Expecter) Tick() *RaftNode_Tick_Call {
	return &RaftNode_Tick_Call{Call: _e.mock.On("Tick")}
}

func (_c *RaftNode_Tick_Call) Run(run func()) *RaftNode_Tick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_Tick_Call) Return() *RaftNode_Tick_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Tick_Call) RunAndReturn(run func()) *RaftNode_Tick_Call {
	_c.Run(run)
	return _c
}
