// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/robinkb/cascade-registry/cluster/raft"
	mock "github.com/stretchr/testify/mock"
	"go.etcd.io/raft/v3/raftpb"
)

// NewRaftNode creates a new instance of RaftNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRaftNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *RaftNode {
	mock := &RaftNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RaftNode is an autogenerated mock type for the Node type
type RaftNode struct {
	mock.Mock
}

type RaftNode_Expecter struct {
	mock *mock.Mock
}

func (_m *RaftNode) EXPECT() *RaftNode_Expecter {
	return &RaftNode_Expecter{mock: &_m.Mock}
}

// ClusterStatus provides a mock function for the type RaftNode
func (_mock *RaftNode) ClusterStatus() raft.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClusterStatus")
	}

	var r0 raft.Status
	if returnFunc, ok := ret.Get(0).(func() raft.Status); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(raft.Status)
	}
	return r0
}

// RaftNode_ClusterStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterStatus'
type RaftNode_ClusterStatus_Call struct {
	*mock.Call
}

// ClusterStatus is a helper method to define mock.On call
func (_e *RaftNode_Expecter) ClusterStatus() *RaftNode_ClusterStatus_Call {
	return &RaftNode_ClusterStatus_Call{Call: _e.mock.On("ClusterStatus")}
}

func (_c *RaftNode_ClusterStatus_Call) Run(run func()) *RaftNode_ClusterStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_ClusterStatus_Call) Return(status raft.Status) *RaftNode_ClusterStatus_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *RaftNode_ClusterStatus_Call) RunAndReturn(run func() raft.Status) *RaftNode_ClusterStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type RaftNode
func (_mock *RaftNode) Commit(data []byte) {
	_mock.Called(data)
	return
}

// RaftNode_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type RaftNode_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - data []byte
func (_e *RaftNode_Expecter) Commit(data interface{}) *RaftNode_Commit_Call {
	return &RaftNode_Commit_Call{Call: _e.mock.On("Commit", data)}
}

func (_c *RaftNode_Commit_Call) Run(run func(data []byte)) *RaftNode_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RaftNode_Commit_Call) Return() *RaftNode_Commit_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Commit_Call) RunAndReturn(run func(data []byte)) *RaftNode_Commit_Call {
	_c.Run(run)
	return _c
}

// Handle provides a mock function for the type RaftNode
func (_mock *RaftNode) Handle(p raft.Proposal, f raft.HandlerFunc) {
	_mock.Called(p, f)
	return
}

// RaftNode_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type RaftNode_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - p raft.Proposal
//   - f raft.HandlerFunc
func (_e *RaftNode_Expecter) Handle(p interface{}, f interface{}) *RaftNode_Handle_Call {
	return &RaftNode_Handle_Call{Call: _e.mock.On("Handle", p, f)}
}

func (_c *RaftNode_Handle_Call) Run(run func(p raft.Proposal, f raft.HandlerFunc)) *RaftNode_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 raft.Proposal
		if args[0] != nil {
			arg0 = args[0].(raft.Proposal)
		}
		var arg1 raft.HandlerFunc
		if args[1] != nil {
			arg1 = args[1].(raft.HandlerFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RaftNode_Handle_Call) Return() *RaftNode_Handle_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Handle_Call) RunAndReturn(run func(p raft.Proposal, f raft.HandlerFunc)) *RaftNode_Handle_Call {
	_c.Run(run)
	return _c
}

// Propose provides a mock function for the type RaftNode
func (_mock *RaftNode) Propose(p raft.Proposal) error {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Propose")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(raft.Proposal) error); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RaftNode_Propose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Propose'
type RaftNode_Propose_Call struct {
	*mock.Call
}

// Propose is a helper method to define mock.On call
//   - p raft.Proposal
func (_e *RaftNode_Expecter) Propose(p interface{}) *RaftNode_Propose_Call {
	return &RaftNode_Propose_Call{Call: _e.mock.On("Propose", p)}
}

func (_c *RaftNode_Propose_Call) Run(run func(p raft.Proposal)) *RaftNode_Propose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 raft.Proposal
		if args[0] != nil {
			arg0 = args[0].(raft.Proposal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RaftNode_Propose_Call) Return(err error) *RaftNode_Propose_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RaftNode_Propose_Call) RunAndReturn(run func(p raft.Proposal) error) *RaftNode_Propose_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type RaftNode
func (_mock *RaftNode) Receive(m *raftpb.Message) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*raftpb.Message) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RaftNode_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type RaftNode_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - m *raftpb.Message
func (_e *RaftNode_Expecter) Receive(m interface{}) *RaftNode_Receive_Call {
	return &RaftNode_Receive_Call{Call: _e.mock.On("Receive", m)}
}

func (_c *RaftNode_Receive_Call) Run(run func(m *raftpb.Message)) *RaftNode_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *raftpb.Message
		if args[0] != nil {
			arg0 = args[0].(*raftpb.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RaftNode_Receive_Call) Return(err error) *RaftNode_Receive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RaftNode_Receive_Call) RunAndReturn(run func(m *raftpb.Message) error) *RaftNode_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type RaftNode
func (_mock *RaftNode) Start() {
	_mock.Called()
	return
}

// RaftNode_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type RaftNode_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *RaftNode_Expecter) Start() *RaftNode_Start_Call {
	return &RaftNode_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *RaftNode_Start_Call) Run(run func()) *RaftNode_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_Start_Call) Return() *RaftNode_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Start_Call) RunAndReturn(run func()) *RaftNode_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type RaftNode
func (_mock *RaftNode) Stop() {
	_mock.Called()
	return
}

// RaftNode_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type RaftNode_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *RaftNode_Expecter) Stop() *RaftNode_Stop_Call {
	return &RaftNode_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *RaftNode_Stop_Call) Run(run func()) *RaftNode_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_Stop_Call) Return() *RaftNode_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Stop_Call) RunAndReturn(run func()) *RaftNode_Stop_Call {
	_c.Run(run)
	return _c
}

// Tick provides a mock function for the type RaftNode
func (_mock *RaftNode) Tick() {
	_mock.Called()
	return
}

// RaftNode_Tick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tick'
type RaftNode_Tick_Call struct {
	*mock.Call
}

// Tick is a helper method to define mock.On call
func (_e *RaftNode_Expecter) Tick() *RaftNode_Tick_Call {
	return &RaftNode_Tick_Call{Call: _e.mock.On("Tick")}
}

func (_c *RaftNode_Tick_Call) Run(run func()) *RaftNode_Tick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RaftNode_Tick_Call) Return() *RaftNode_Tick_Call {
	_c.Call.Return()
	return _c
}

func (_c *RaftNode_Tick_Call) RunAndReturn(run func()) *RaftNode_Tick_Call {
	_c.Run(run)
	return _c
}
