// Code generated by mockery. DO NOT EDIT.

package mock

import (
	repository "github.com/robinkb/cascade-registry/repository"
	mock "github.com/stretchr/testify/mock"
)

// RegistryService is an autogenerated mock type for the RegistryService type
type RegistryService struct {
	mock.Mock
}

type RegistryService_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistryService) EXPECT() *RegistryService_Expecter {
	return &RegistryService_Expecter{mock: &_m.Mock}
}

// GetRepository provides a mock function with given fields: name
func (_m *RegistryService) GetRepository(name string) (repository.RepositoryService, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 repository.RepositoryService
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (repository.RepositoryService, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) repository.RepositoryService); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.RepositoryService)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryService_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type RegistryService_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
//   - name string
func (_e *RegistryService_Expecter) GetRepository(name interface{}) *RegistryService_GetRepository_Call {
	return &RegistryService_GetRepository_Call{Call: _e.mock.On("GetRepository", name)}
}

func (_c *RegistryService_GetRepository_Call) Run(run func(name string)) *RegistryService_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RegistryService_GetRepository_Call) Return(_a0 repository.RepositoryService, _a1 error) *RegistryService_GetRepository_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryService_GetRepository_Call) RunAndReturn(run func(string) (repository.RepositoryService, error)) *RegistryService_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewRegistryService creates a new instance of RegistryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryService {
	mock := &RegistryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
