// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/robinkb/cascade-registry/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewRegistryService creates a new instance of RegistryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryService {
	mock := &RegistryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RegistryService is an autogenerated mock type for the RegistryService type
type RegistryService struct {
	mock.Mock
}

type RegistryService_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistryService) EXPECT() *RegistryService_Expecter {
	return &RegistryService_Expecter{mock: &_m.Mock}
}

// CreateRepository provides a mock function for the type RegistryService
func (_mock *RegistryService) CreateRepository(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RegistryService_CreateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRepository'
type RegistryService_CreateRepository_Call struct {
	*mock.Call
}

// CreateRepository is a helper method to define mock.On call
//   - name string
func (_e *RegistryService_Expecter) CreateRepository(name interface{}) *RegistryService_CreateRepository_Call {
	return &RegistryService_CreateRepository_Call{Call: _e.mock.On("CreateRepository", name)}
}

func (_c *RegistryService_CreateRepository_Call) Run(run func(name string)) *RegistryService_CreateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RegistryService_CreateRepository_Call) Return(err error) *RegistryService_CreateRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RegistryService_CreateRepository_Call) RunAndReturn(run func(name string) error) *RegistryService_CreateRepository_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRepository provides a mock function for the type RegistryService
func (_mock *RegistryService) DeleteRepository(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRepository")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RegistryService_DeleteRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRepository'
type RegistryService_DeleteRepository_Call struct {
	*mock.Call
}

// DeleteRepository is a helper method to define mock.On call
//   - name string
func (_e *RegistryService_Expecter) DeleteRepository(name interface{}) *RegistryService_DeleteRepository_Call {
	return &RegistryService_DeleteRepository_Call{Call: _e.mock.On("DeleteRepository", name)}
}

func (_c *RegistryService_DeleteRepository_Call) Run(run func(name string)) *RegistryService_DeleteRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RegistryService_DeleteRepository_Call) Return(err error) *RegistryService_DeleteRepository_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RegistryService_DeleteRepository_Call) RunAndReturn(run func(name string) error) *RegistryService_DeleteRepository_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepository provides a mock function for the type RegistryService
func (_mock *RegistryService) GetRepository(name string) (repository.RepositoryService, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetRepository")
	}

	var r0 repository.RepositoryService
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (repository.RepositoryService, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) repository.RepositoryService); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.RepositoryService)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RegistryService_GetRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepository'
type RegistryService_GetRepository_Call struct {
	*mock.Call
}

// GetRepository is a helper method to define mock.On call
//   - name string
func (_e *RegistryService_Expecter) GetRepository(name interface{}) *RegistryService_GetRepository_Call {
	return &RegistryService_GetRepository_Call{Call: _e.mock.On("GetRepository", name)}
}

func (_c *RegistryService_GetRepository_Call) Run(run func(name string)) *RegistryService_GetRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RegistryService_GetRepository_Call) Return(repositoryService repository.RepositoryService, err error) *RegistryService_GetRepository_Call {
	_c.Call.Return(repositoryService, err)
	return _c
}

func (_c *RegistryService_GetRepository_Call) RunAndReturn(run func(name string) (repository.RepositoryService, error)) *RegistryService_GetRepository_Call {
	_c.Call.Return(run)
	return _c
}
