// Code generated by mockery. DO NOT EDIT.

package mock

import (
	io "io"

	cascade "github.com/robinkb/cascade-registry"

	mock "github.com/stretchr/testify/mock"
)

// RegistryService is an autogenerated mock type for the RegistryService type
type RegistryService struct {
	mock.Mock
}

type RegistryService_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistryService) EXPECT() *RegistryService_Expecter {
	return &RegistryService_Expecter{mock: &_m.Mock}
}

// AppendUpload provides a mock function with given fields: repository, sessionID, r, offset
func (_m *RegistryService) AppendUpload(repository string, sessionID string, r io.Reader, offset int64) error {
	ret := _m.Called(repository, sessionID, r, offset)

	if len(ret) == 0 {
		panic("no return value specified for AppendUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, io.Reader, int64) error); ok {
		r0 = rf(repository, sessionID, r, offset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistryService_AppendUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendUpload'
type RegistryService_AppendUpload_Call struct {
	*mock.Call
}

// AppendUpload is a helper method to define mock.On call
//   - repository string
//   - sessionID string
//   - r io.Reader
//   - offset int64
func (_e *RegistryService_Expecter) AppendUpload(repository interface{}, sessionID interface{}, r interface{}, offset interface{}) *RegistryService_AppendUpload_Call {
	return &RegistryService_AppendUpload_Call{Call: _e.mock.On("AppendUpload", repository, sessionID, r, offset)}
}

func (_c *RegistryService_AppendUpload_Call) Run(run func(repository string, sessionID string, r io.Reader, offset int64)) *RegistryService_AppendUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(io.Reader), args[3].(int64))
	})
	return _c
}

func (_c *RegistryService_AppendUpload_Call) Return(_a0 error) *RegistryService_AppendUpload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistryService_AppendUpload_Call) RunAndReturn(run func(string, string, io.Reader, int64) error) *RegistryService_AppendUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CloseUpload provides a mock function with given fields: repository, id, digest
func (_m *RegistryService) CloseUpload(repository string, id string, digest string) error {
	ret := _m.Called(repository, id, digest)

	if len(ret) == 0 {
		panic("no return value specified for CloseUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(repository, id, digest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistryService_CloseUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseUpload'
type RegistryService_CloseUpload_Call struct {
	*mock.Call
}

// CloseUpload is a helper method to define mock.On call
//   - repository string
//   - id string
//   - digest string
func (_e *RegistryService_Expecter) CloseUpload(repository interface{}, id interface{}, digest interface{}) *RegistryService_CloseUpload_Call {
	return &RegistryService_CloseUpload_Call{Call: _e.mock.On("CloseUpload", repository, id, digest)}
}

func (_c *RegistryService_CloseUpload_Call) Run(run func(repository string, id string, digest string)) *RegistryService_CloseUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RegistryService_CloseUpload_Call) Return(_a0 error) *RegistryService_CloseUpload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistryService_CloseUpload_Call) RunAndReturn(run func(string, string, string) error) *RegistryService_CloseUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlob provides a mock function with given fields: repository, digest
func (_m *RegistryService) DeleteBlob(repository string, digest string) error {
	ret := _m.Called(repository, digest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(repository, digest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistryService_DeleteBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlob'
type RegistryService_DeleteBlob_Call struct {
	*mock.Call
}

// DeleteBlob is a helper method to define mock.On call
//   - repository string
//   - digest string
func (_e *RegistryService_Expecter) DeleteBlob(repository interface{}, digest interface{}) *RegistryService_DeleteBlob_Call {
	return &RegistryService_DeleteBlob_Call{Call: _e.mock.On("DeleteBlob", repository, digest)}
}

func (_c *RegistryService_DeleteBlob_Call) Run(run func(repository string, digest string)) *RegistryService_DeleteBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RegistryService_DeleteBlob_Call) Return(_a0 error) *RegistryService_DeleteBlob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistryService_DeleteBlob_Call) RunAndReturn(run func(string, string) error) *RegistryService_DeleteBlob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteManifest provides a mock function with given fields: repository, reference
func (_m *RegistryService) DeleteManifest(repository string, reference string) error {
	ret := _m.Called(repository, reference)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManifest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(repository, reference)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistryService_DeleteManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManifest'
type RegistryService_DeleteManifest_Call struct {
	*mock.Call
}

// DeleteManifest is a helper method to define mock.On call
//   - repository string
//   - reference string
func (_e *RegistryService_Expecter) DeleteManifest(repository interface{}, reference interface{}) *RegistryService_DeleteManifest_Call {
	return &RegistryService_DeleteManifest_Call{Call: _e.mock.On("DeleteManifest", repository, reference)}
}

func (_c *RegistryService_DeleteManifest_Call) Run(run func(repository string, reference string)) *RegistryService_DeleteManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RegistryService_DeleteManifest_Call) Return(_a0 error) *RegistryService_DeleteManifest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistryService_DeleteManifest_Call) RunAndReturn(run func(string, string) error) *RegistryService_DeleteManifest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function with given fields: repository, tag
func (_m *RegistryService) DeleteTag(repository string, tag string) error {
	ret := _m.Called(repository, tag)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(repository, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistryService_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type RegistryService_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - repository string
//   - tag string
func (_e *RegistryService_Expecter) DeleteTag(repository interface{}, tag interface{}) *RegistryService_DeleteTag_Call {
	return &RegistryService_DeleteTag_Call{Call: _e.mock.On("DeleteTag", repository, tag)}
}

func (_c *RegistryService_DeleteTag_Call) Run(run func(repository string, tag string)) *RegistryService_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RegistryService_DeleteTag_Call) Return(_a0 error) *RegistryService_DeleteTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistryService_DeleteTag_Call) RunAndReturn(run func(string, string) error) *RegistryService_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlob provides a mock function with given fields: repository, digest
func (_m *RegistryService) GetBlob(repository string, digest string) (io.Reader, error) {
	ret := _m.Called(repository, digest)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (io.Reader, error)); ok {
		return rf(repository, digest)
	}
	if rf, ok := ret.Get(0).(func(string, string) io.Reader); ok {
		r0 = rf(repository, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(repository, digest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryService_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type RegistryService_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - repository string
//   - digest string
func (_e *RegistryService_Expecter) GetBlob(repository interface{}, digest interface{}) *RegistryService_GetBlob_Call {
	return &RegistryService_GetBlob_Call{Call: _e.mock.On("GetBlob", repository, digest)}
}

func (_c *RegistryService_GetBlob_Call) Run(run func(repository string, digest string)) *RegistryService_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RegistryService_GetBlob_Call) Return(_a0 io.Reader, _a1 error) *RegistryService_GetBlob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryService_GetBlob_Call) RunAndReturn(run func(string, string) (io.Reader, error)) *RegistryService_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// GetManifest provides a mock function with given fields: repository, reference
func (_m *RegistryService) GetManifest(repository string, reference string) (*cascade.ManifestMetadata, []byte, error) {
	ret := _m.Called(repository, reference)

	if len(ret) == 0 {
		panic("no return value specified for GetManifest")
	}

	var r0 *cascade.ManifestMetadata
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (*cascade.ManifestMetadata, []byte, error)); ok {
		return rf(repository, reference)
	}
	if rf, ok := ret.Get(0).(func(string, string) *cascade.ManifestMetadata); ok {
		r0 = rf(repository, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cascade.ManifestMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) []byte); ok {
		r1 = rf(repository, reference)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(repository, reference)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RegistryService_GetManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManifest'
type RegistryService_GetManifest_Call struct {
	*mock.Call
}

// GetManifest is a helper method to define mock.On call
//   - repository string
//   - reference string
func (_e *RegistryService_Expecter) GetManifest(repository interface{}, reference interface{}) *RegistryService_GetManifest_Call {
	return &RegistryService_GetManifest_Call{Call: _e.mock.On("GetManifest", repository, reference)}
}

func (_c *RegistryService_GetManifest_Call) Run(run func(repository string, reference string)) *RegistryService_GetManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RegistryService_GetManifest_Call) Return(_a0 *cascade.ManifestMetadata, _a1 []byte, _a2 error) *RegistryService_GetManifest_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *RegistryService_GetManifest_Call) RunAndReturn(run func(string, string) (*cascade.ManifestMetadata, []byte, error)) *RegistryService_GetManifest_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function with given fields: repository, tag
func (_m *RegistryService) GetTag(repository string, tag string) (string, error) {
	ret := _m.Called(repository, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(repository, tag)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(repository, tag)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(repository, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryService_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type RegistryService_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
//   - repository string
//   - tag string
func (_e *RegistryService_Expecter) GetTag(repository interface{}, tag interface{}) *RegistryService_GetTag_Call {
	return &RegistryService_GetTag_Call{Call: _e.mock.On("GetTag", repository, tag)}
}

func (_c *RegistryService_GetTag_Call) Run(run func(repository string, tag string)) *RegistryService_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RegistryService_GetTag_Call) Return(_a0 string, _a1 error) *RegistryService_GetTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryService_GetTag_Call) RunAndReturn(run func(string, string) (string, error)) *RegistryService_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// InitUpload provides a mock function with given fields: repository
func (_m *RegistryService) InitUpload(repository string) *cascade.UploadSession {
	ret := _m.Called(repository)

	if len(ret) == 0 {
		panic("no return value specified for InitUpload")
	}

	var r0 *cascade.UploadSession
	if rf, ok := ret.Get(0).(func(string) *cascade.UploadSession); ok {
		r0 = rf(repository)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cascade.UploadSession)
		}
	}

	return r0
}

// RegistryService_InitUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitUpload'
type RegistryService_InitUpload_Call struct {
	*mock.Call
}

// InitUpload is a helper method to define mock.On call
//   - repository string
func (_e *RegistryService_Expecter) InitUpload(repository interface{}) *RegistryService_InitUpload_Call {
	return &RegistryService_InitUpload_Call{Call: _e.mock.On("InitUpload", repository)}
}

func (_c *RegistryService_InitUpload_Call) Run(run func(repository string)) *RegistryService_InitUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RegistryService_InitUpload_Call) Return(_a0 *cascade.UploadSession) *RegistryService_InitUpload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistryService_InitUpload_Call) RunAndReturn(run func(string) *cascade.UploadSession) *RegistryService_InitUpload_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function with given fields: repository, count, from
func (_m *RegistryService) ListTags(repository string, count int, from string) ([]string, error) {
	ret := _m.Called(repository, count, from)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, string) ([]string, error)); ok {
		return rf(repository, count, from)
	}
	if rf, ok := ret.Get(0).(func(string, int, string) []string); ok {
		r0 = rf(repository, count, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, string) error); ok {
		r1 = rf(repository, count, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryService_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type RegistryService_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - repository string
//   - count int
//   - from string
func (_e *RegistryService_Expecter) ListTags(repository interface{}, count interface{}, from interface{}) *RegistryService_ListTags_Call {
	return &RegistryService_ListTags_Call{Call: _e.mock.On("ListTags", repository, count, from)}
}

func (_c *RegistryService_ListTags_Call) Run(run func(repository string, count int, from string)) *RegistryService_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *RegistryService_ListTags_Call) Return(_a0 []string, _a1 error) *RegistryService_ListTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryService_ListTags_Call) RunAndReturn(run func(string, int, string) ([]string, error)) *RegistryService_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// PutManifest provides a mock function with given fields: repository, reference, content
func (_m *RegistryService) PutManifest(repository string, reference string, content []byte) error {
	ret := _m.Called(repository, reference, content)

	if len(ret) == 0 {
		panic("no return value specified for PutManifest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []byte) error); ok {
		r0 = rf(repository, reference, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistryService_PutManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutManifest'
type RegistryService_PutManifest_Call struct {
	*mock.Call
}

// PutManifest is a helper method to define mock.On call
//   - repository string
//   - reference string
//   - content []byte
func (_e *RegistryService_Expecter) PutManifest(repository interface{}, reference interface{}, content interface{}) *RegistryService_PutManifest_Call {
	return &RegistryService_PutManifest_Call{Call: _e.mock.On("PutManifest", repository, reference, content)}
}

func (_c *RegistryService_PutManifest_Call) Run(run func(repository string, reference string, content []byte)) *RegistryService_PutManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *RegistryService_PutManifest_Call) Return(_a0 error) *RegistryService_PutManifest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistryService_PutManifest_Call) RunAndReturn(run func(string, string, []byte) error) *RegistryService_PutManifest_Call {
	_c.Call.Return(run)
	return _c
}

// PutTag provides a mock function with given fields: repository, tag, digest
func (_m *RegistryService) PutTag(repository string, tag string, digest string) error {
	ret := _m.Called(repository, tag, digest)

	if len(ret) == 0 {
		panic("no return value specified for PutTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(repository, tag, digest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegistryService_PutTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutTag'
type RegistryService_PutTag_Call struct {
	*mock.Call
}

// PutTag is a helper method to define mock.On call
//   - repository string
//   - tag string
//   - digest string
func (_e *RegistryService_Expecter) PutTag(repository interface{}, tag interface{}, digest interface{}) *RegistryService_PutTag_Call {
	return &RegistryService_PutTag_Call{Call: _e.mock.On("PutTag", repository, tag, digest)}
}

func (_c *RegistryService_PutTag_Call) Run(run func(repository string, tag string, digest string)) *RegistryService_PutTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RegistryService_PutTag_Call) Return(_a0 error) *RegistryService_PutTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RegistryService_PutTag_Call) RunAndReturn(run func(string, string, string) error) *RegistryService_PutTag_Call {
	_c.Call.Return(run)
	return _c
}

// StatBlob provides a mock function with given fields: repository, digest
func (_m *RegistryService) StatBlob(repository string, digest string) (*cascade.FileInfo, error) {
	ret := _m.Called(repository, digest)

	if len(ret) == 0 {
		panic("no return value specified for StatBlob")
	}

	var r0 *cascade.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*cascade.FileInfo, error)); ok {
		return rf(repository, digest)
	}
	if rf, ok := ret.Get(0).(func(string, string) *cascade.FileInfo); ok {
		r0 = rf(repository, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cascade.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(repository, digest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryService_StatBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatBlob'
type RegistryService_StatBlob_Call struct {
	*mock.Call
}

// StatBlob is a helper method to define mock.On call
//   - repository string
//   - digest string
func (_e *RegistryService_Expecter) StatBlob(repository interface{}, digest interface{}) *RegistryService_StatBlob_Call {
	return &RegistryService_StatBlob_Call{Call: _e.mock.On("StatBlob", repository, digest)}
}

func (_c *RegistryService_StatBlob_Call) Run(run func(repository string, digest string)) *RegistryService_StatBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RegistryService_StatBlob_Call) Return(_a0 *cascade.FileInfo, _a1 error) *RegistryService_StatBlob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryService_StatBlob_Call) RunAndReturn(run func(string, string) (*cascade.FileInfo, error)) *RegistryService_StatBlob_Call {
	_c.Call.Return(run)
	return _c
}

// StatManifest provides a mock function with given fields: repository, reference
func (_m *RegistryService) StatManifest(repository string, reference string) (*cascade.FileInfo, error) {
	ret := _m.Called(repository, reference)

	if len(ret) == 0 {
		panic("no return value specified for StatManifest")
	}

	var r0 *cascade.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*cascade.FileInfo, error)); ok {
		return rf(repository, reference)
	}
	if rf, ok := ret.Get(0).(func(string, string) *cascade.FileInfo); ok {
		r0 = rf(repository, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cascade.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(repository, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryService_StatManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatManifest'
type RegistryService_StatManifest_Call struct {
	*mock.Call
}

// StatManifest is a helper method to define mock.On call
//   - repository string
//   - reference string
func (_e *RegistryService_Expecter) StatManifest(repository interface{}, reference interface{}) *RegistryService_StatManifest_Call {
	return &RegistryService_StatManifest_Call{Call: _e.mock.On("StatManifest", repository, reference)}
}

func (_c *RegistryService_StatManifest_Call) Run(run func(repository string, reference string)) *RegistryService_StatManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RegistryService_StatManifest_Call) Return(_a0 *cascade.FileInfo, _a1 error) *RegistryService_StatManifest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryService_StatManifest_Call) RunAndReturn(run func(string, string) (*cascade.FileInfo, error)) *RegistryService_StatManifest_Call {
	_c.Call.Return(run)
	return _c
}

// StatUpload provides a mock function with given fields: repository, sessionID
func (_m *RegistryService) StatUpload(repository string, sessionID string) (*cascade.FileInfo, error) {
	ret := _m.Called(repository, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for StatUpload")
	}

	var r0 *cascade.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*cascade.FileInfo, error)); ok {
		return rf(repository, sessionID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *cascade.FileInfo); ok {
		r0 = rf(repository, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cascade.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(repository, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryService_StatUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatUpload'
type RegistryService_StatUpload_Call struct {
	*mock.Call
}

// StatUpload is a helper method to define mock.On call
//   - repository string
//   - sessionID string
func (_e *RegistryService_Expecter) StatUpload(repository interface{}, sessionID interface{}) *RegistryService_StatUpload_Call {
	return &RegistryService_StatUpload_Call{Call: _e.mock.On("StatUpload", repository, sessionID)}
}

func (_c *RegistryService_StatUpload_Call) Run(run func(repository string, sessionID string)) *RegistryService_StatUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RegistryService_StatUpload_Call) Return(_a0 *cascade.FileInfo, _a1 error) *RegistryService_StatUpload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryService_StatUpload_Call) RunAndReturn(run func(string, string) (*cascade.FileInfo, error)) *RegistryService_StatUpload_Call {
	_c.Call.Return(run)
	return _c
}

// NewRegistryService creates a new instance of RegistryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryService {
	mock := &RegistryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
