// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"io"

	"github.com/opencontainers/go-digest"
	"github.com/robinkb/cascade-registry/registry/repository"
	"github.com/robinkb/cascade-registry/registry/store"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoryService creates a new instance of RepositoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryService {
	mock := &RepositoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryService is an autogenerated mock type for the Service type
type RepositoryService struct {
	mock.Mock
}

type RepositoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryService) EXPECT() *RepositoryService_Expecter {
	return &RepositoryService_Expecter{mock: &_m.Mock}
}

// AppendUpload provides a mock function for the type RepositoryService
func (_mock *RepositoryService) AppendUpload(repository string, sessionID string, r io.Reader, offset int64) error {
	ret := _mock.Called(repository, sessionID, r, offset)

	if len(ret) == 0 {
		panic("no return value specified for AppendUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, io.Reader, int64) error); ok {
		r0 = returnFunc(repository, sessionID, r, offset)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryService_AppendUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendUpload'
type RepositoryService_AppendUpload_Call struct {
	*mock.Call
}

// AppendUpload is a helper method to define mock.On call
//   - repository string
//   - sessionID string
//   - r io.Reader
//   - offset int64
func (_e *RepositoryService_Expecter) AppendUpload(repository interface{}, sessionID interface{}, r interface{}, offset interface{}) *RepositoryService_AppendUpload_Call {
	return &RepositoryService_AppendUpload_Call{Call: _e.mock.On("AppendUpload", repository, sessionID, r, offset)}
}

func (_c *RepositoryService_AppendUpload_Call) Run(run func(repository string, sessionID string, r io.Reader, offset int64)) *RepositoryService_AppendUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RepositoryService_AppendUpload_Call) Return(err error) *RepositoryService_AppendUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryService_AppendUpload_Call) RunAndReturn(run func(repository string, sessionID string, r io.Reader, offset int64) error) *RepositoryService_AppendUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CloseUpload provides a mock function for the type RepositoryService
func (_mock *RepositoryService) CloseUpload(repository string, id string, digest string) error {
	ret := _mock.Called(repository, id, digest)

	if len(ret) == 0 {
		panic("no return value specified for CloseUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(repository, id, digest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryService_CloseUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseUpload'
type RepositoryService_CloseUpload_Call struct {
	*mock.Call
}

// CloseUpload is a helper method to define mock.On call
//   - repository string
//   - id string
//   - digest string
func (_e *RepositoryService_Expecter) CloseUpload(repository interface{}, id interface{}, digest interface{}) *RepositoryService_CloseUpload_Call {
	return &RepositoryService_CloseUpload_Call{Call: _e.mock.On("CloseUpload", repository, id, digest)}
}

func (_c *RepositoryService_CloseUpload_Call) Run(run func(repository string, id string, digest string)) *RepositoryService_CloseUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RepositoryService_CloseUpload_Call) Return(err error) *RepositoryService_CloseUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryService_CloseUpload_Call) RunAndReturn(run func(repository string, id string, digest string) error) *RepositoryService_CloseUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlob provides a mock function for the type RepositoryService
func (_mock *RepositoryService) DeleteBlob(repository string, digest string) error {
	ret := _mock.Called(repository, digest)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlob")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(repository, digest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryService_DeleteBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlob'
type RepositoryService_DeleteBlob_Call struct {
	*mock.Call
}

// DeleteBlob is a helper method to define mock.On call
//   - repository string
//   - digest string
func (_e *RepositoryService_Expecter) DeleteBlob(repository interface{}, digest interface{}) *RepositoryService_DeleteBlob_Call {
	return &RepositoryService_DeleteBlob_Call{Call: _e.mock.On("DeleteBlob", repository, digest)}
}

func (_c *RepositoryService_DeleteBlob_Call) Run(run func(repository string, digest string)) *RepositoryService_DeleteBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryService_DeleteBlob_Call) Return(err error) *RepositoryService_DeleteBlob_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryService_DeleteBlob_Call) RunAndReturn(run func(repository string, digest string) error) *RepositoryService_DeleteBlob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteManifest provides a mock function for the type RepositoryService
func (_mock *RepositoryService) DeleteManifest(repository string, reference string) error {
	ret := _mock.Called(repository, reference)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManifest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(repository, reference)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryService_DeleteManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManifest'
type RepositoryService_DeleteManifest_Call struct {
	*mock.Call
}

// DeleteManifest is a helper method to define mock.On call
//   - repository string
//   - reference string
func (_e *RepositoryService_Expecter) DeleteManifest(repository interface{}, reference interface{}) *RepositoryService_DeleteManifest_Call {
	return &RepositoryService_DeleteManifest_Call{Call: _e.mock.On("DeleteManifest", repository, reference)}
}

func (_c *RepositoryService_DeleteManifest_Call) Run(run func(repository string, reference string)) *RepositoryService_DeleteManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryService_DeleteManifest_Call) Return(err error) *RepositoryService_DeleteManifest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryService_DeleteManifest_Call) RunAndReturn(run func(repository string, reference string) error) *RepositoryService_DeleteManifest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function for the type RepositoryService
func (_mock *RepositoryService) DeleteTag(repository string, tag string) error {
	ret := _mock.Called(repository, tag)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(repository, tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryService_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type RepositoryService_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - repository string
//   - tag string
func (_e *RepositoryService_Expecter) DeleteTag(repository interface{}, tag interface{}) *RepositoryService_DeleteTag_Call {
	return &RepositoryService_DeleteTag_Call{Call: _e.mock.On("DeleteTag", repository, tag)}
}

func (_c *RepositoryService_DeleteTag_Call) Run(run func(repository string, tag string)) *RepositoryService_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryService_DeleteTag_Call) Return(err error) *RepositoryService_DeleteTag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryService_DeleteTag_Call) RunAndReturn(run func(repository string, tag string) error) *RepositoryService_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlob provides a mock function for the type RepositoryService
func (_mock *RepositoryService) GetBlob(repository string, digest string) (io.Reader, error) {
	ret := _mock.Called(repository, digest)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 io.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (io.Reader, error)); ok {
		return returnFunc(repository, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) io.Reader); ok {
		r0 = returnFunc(repository, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(repository, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryService_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type RepositoryService_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - repository string
//   - digest string
func (_e *RepositoryService_Expecter) GetBlob(repository interface{}, digest interface{}) *RepositoryService_GetBlob_Call {
	return &RepositoryService_GetBlob_Call{Call: _e.mock.On("GetBlob", repository, digest)}
}

func (_c *RepositoryService_GetBlob_Call) Run(run func(repository string, digest string)) *RepositoryService_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryService_GetBlob_Call) Return(reader io.Reader, err error) *RepositoryService_GetBlob_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *RepositoryService_GetBlob_Call) RunAndReturn(run func(repository string, digest string) (io.Reader, error)) *RepositoryService_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// GetManifest provides a mock function for the type RepositoryService
func (_mock *RepositoryService) GetManifest(repository string, reference string) (*store.ManifestMetadata, []byte, error) {
	ret := _mock.Called(repository, reference)

	if len(ret) == 0 {
		panic("no return value specified for GetManifest")
	}

	var r0 *store.ManifestMetadata
	var r1 []byte
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*store.ManifestMetadata, []byte, error)); ok {
		return returnFunc(repository, reference)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *store.ManifestMetadata); ok {
		r0 = returnFunc(repository, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.ManifestMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) []byte); ok {
		r1 = returnFunc(repository, reference)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(repository, reference)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// RepositoryService_GetManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManifest'
type RepositoryService_GetManifest_Call struct {
	*mock.Call
}

// GetManifest is a helper method to define mock.On call
//   - repository string
//   - reference string
func (_e *RepositoryService_Expecter) GetManifest(repository interface{}, reference interface{}) *RepositoryService_GetManifest_Call {
	return &RepositoryService_GetManifest_Call{Call: _e.mock.On("GetManifest", repository, reference)}
}

func (_c *RepositoryService_GetManifest_Call) Run(run func(repository string, reference string)) *RepositoryService_GetManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryService_GetManifest_Call) Return(manifestMetadata *store.ManifestMetadata, bytes []byte, err error) *RepositoryService_GetManifest_Call {
	_c.Call.Return(manifestMetadata, bytes, err)
	return _c
}

func (_c *RepositoryService_GetManifest_Call) RunAndReturn(run func(repository string, reference string) (*store.ManifestMetadata, []byte, error)) *RepositoryService_GetManifest_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function for the type RepositoryService
func (_mock *RepositoryService) GetTag(repository string, tag string) (string, error) {
	ret := _mock.Called(repository, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(repository, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(repository, tag)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(repository, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryService_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type RepositoryService_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
//   - repository string
//   - tag string
func (_e *RepositoryService_Expecter) GetTag(repository interface{}, tag interface{}) *RepositoryService_GetTag_Call {
	return &RepositoryService_GetTag_Call{Call: _e.mock.On("GetTag", repository, tag)}
}

func (_c *RepositoryService_GetTag_Call) Run(run func(repository string, tag string)) *RepositoryService_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryService_GetTag_Call) Return(s string, err error) *RepositoryService_GetTag_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *RepositoryService_GetTag_Call) RunAndReturn(run func(repository string, tag string) (string, error)) *RepositoryService_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// InitUpload provides a mock function for the type RepositoryService
func (_mock *RepositoryService) InitUpload(repository string) (*store.UploadSession, error) {
	ret := _mock.Called(repository)

	if len(ret) == 0 {
		panic("no return value specified for InitUpload")
	}

	var r0 *store.UploadSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*store.UploadSession, error)); ok {
		return returnFunc(repository)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *store.UploadSession); ok {
		r0 = returnFunc(repository)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.UploadSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(repository)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryService_InitUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitUpload'
type RepositoryService_InitUpload_Call struct {
	*mock.Call
}

// InitUpload is a helper method to define mock.On call
//   - repository string
func (_e *RepositoryService_Expecter) InitUpload(repository interface{}) *RepositoryService_InitUpload_Call {
	return &RepositoryService_InitUpload_Call{Call: _e.mock.On("InitUpload", repository)}
}

func (_c *RepositoryService_InitUpload_Call) Run(run func(repository string)) *RepositoryService_InitUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RepositoryService_InitUpload_Call) Return(uploadSession *store.UploadSession, err error) *RepositoryService_InitUpload_Call {
	_c.Call.Return(uploadSession, err)
	return _c
}

func (_c *RepositoryService_InitUpload_Call) RunAndReturn(run func(repository string) (*store.UploadSession, error)) *RepositoryService_InitUpload_Call {
	_c.Call.Return(run)
	return _c
}

// ListReferrers provides a mock function for the type RepositoryService
func (_mock *RepositoryService) ListReferrers(repository1 string, digest string, opts *repository.ListReferrersOptions) (*repository.Referrers, error) {
	ret := _mock.Called(repository1, digest, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListReferrers")
	}

	var r0 *repository.Referrers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *repository.ListReferrersOptions) (*repository.Referrers, error)); ok {
		return returnFunc(repository1, digest, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *repository.ListReferrersOptions) *repository.Referrers); ok {
		r0 = returnFunc(repository1, digest, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Referrers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *repository.ListReferrersOptions) error); ok {
		r1 = returnFunc(repository1, digest, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryService_ListReferrers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReferrers'
type RepositoryService_ListReferrers_Call struct {
	*mock.Call
}

// ListReferrers is a helper method to define mock.On call
//   - repository1 string
//   - digest string
//   - opts *repository.ListReferrersOptions
func (_e *RepositoryService_Expecter) ListReferrers(repository1 interface{}, digest interface{}, opts interface{}) *RepositoryService_ListReferrers_Call {
	return &RepositoryService_ListReferrers_Call{Call: _e.mock.On("ListReferrers", repository1, digest, opts)}
}

func (_c *RepositoryService_ListReferrers_Call) Run(run func(repository1 string, digest string, opts *repository.ListReferrersOptions)) *RepositoryService_ListReferrers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *repository.ListReferrersOptions
		if args[2] != nil {
			arg2 = args[2].(*repository.ListReferrersOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RepositoryService_ListReferrers_Call) Return(referrers *repository.Referrers, err error) *RepositoryService_ListReferrers_Call {
	_c.Call.Return(referrers, err)
	return _c
}

func (_c *RepositoryService_ListReferrers_Call) RunAndReturn(run func(repository1 string, digest string, opts *repository.ListReferrersOptions) (*repository.Referrers, error)) *RepositoryService_ListReferrers_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function for the type RepositoryService
func (_mock *RepositoryService) ListTags(repository1 string, count int, from string) ([]string, error) {
	ret := _mock.Called(repository1, count, from)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, string) ([]string, error)); ok {
		return returnFunc(repository1, count, from)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, string) []string); ok {
		r0 = returnFunc(repository1, count, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, string) error); ok {
		r1 = returnFunc(repository1, count, from)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryService_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type RepositoryService_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - repository1 string
//   - count int
//   - from string
func (_e *RepositoryService_Expecter) ListTags(repository1 interface{}, count interface{}, from interface{}) *RepositoryService_ListTags_Call {
	return &RepositoryService_ListTags_Call{Call: _e.mock.On("ListTags", repository1, count, from)}
}

func (_c *RepositoryService_ListTags_Call) Run(run func(repository1 string, count int, from string)) *RepositoryService_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RepositoryService_ListTags_Call) Return(strings []string, err error) *RepositoryService_ListTags_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *RepositoryService_ListTags_Call) RunAndReturn(run func(repository1 string, count int, from string) ([]string, error)) *RepositoryService_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// PutManifest provides a mock function for the type RepositoryService
func (_mock *RepositoryService) PutManifest(repository1 string, reference string, content []byte) (digest.Digest, error) {
	ret := _mock.Called(repository1, reference, content)

	if len(ret) == 0 {
		panic("no return value specified for PutManifest")
	}

	var r0 digest.Digest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []byte) (digest.Digest, error)); ok {
		return returnFunc(repository1, reference, content)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, []byte) digest.Digest); ok {
		r0 = returnFunc(repository1, reference, content)
	} else {
		r0 = ret.Get(0).(digest.Digest)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, []byte) error); ok {
		r1 = returnFunc(repository1, reference, content)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryService_PutManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutManifest'
type RepositoryService_PutManifest_Call struct {
	*mock.Call
}

// PutManifest is a helper method to define mock.On call
//   - repository1 string
//   - reference string
//   - content []byte
func (_e *RepositoryService_Expecter) PutManifest(repository1 interface{}, reference interface{}, content interface{}) *RepositoryService_PutManifest_Call {
	return &RepositoryService_PutManifest_Call{Call: _e.mock.On("PutManifest", repository1, reference, content)}
}

func (_c *RepositoryService_PutManifest_Call) Run(run func(repository1 string, reference string, content []byte)) *RepositoryService_PutManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RepositoryService_PutManifest_Call) Return(digest1 digest.Digest, err error) *RepositoryService_PutManifest_Call {
	_c.Call.Return(digest1, err)
	return _c
}

func (_c *RepositoryService_PutManifest_Call) RunAndReturn(run func(repository1 string, reference string, content []byte) (digest.Digest, error)) *RepositoryService_PutManifest_Call {
	_c.Call.Return(run)
	return _c
}

// PutTag provides a mock function for the type RepositoryService
func (_mock *RepositoryService) PutTag(repository1 string, tag string, digest1 string) error {
	ret := _mock.Called(repository1, tag, digest1)

	if len(ret) == 0 {
		panic("no return value specified for PutTag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(repository1, tag, digest1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryService_PutTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutTag'
type RepositoryService_PutTag_Call struct {
	*mock.Call
}

// PutTag is a helper method to define mock.On call
//   - repository1 string
//   - tag string
//   - digest1 string
func (_e *RepositoryService_Expecter) PutTag(repository1 interface{}, tag interface{}, digest1 interface{}) *RepositoryService_PutTag_Call {
	return &RepositoryService_PutTag_Call{Call: _e.mock.On("PutTag", repository1, tag, digest1)}
}

func (_c *RepositoryService_PutTag_Call) Run(run func(repository1 string, tag string, digest1 string)) *RepositoryService_PutTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RepositoryService_PutTag_Call) Return(err error) *RepositoryService_PutTag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryService_PutTag_Call) RunAndReturn(run func(repository1 string, tag string, digest1 string) error) *RepositoryService_PutTag_Call {
	_c.Call.Return(run)
	return _c
}

// StatBlob provides a mock function for the type RepositoryService
func (_mock *RepositoryService) StatBlob(repository1 string, digest1 string) (*store.BlobInfo, error) {
	ret := _mock.Called(repository1, digest1)

	if len(ret) == 0 {
		panic("no return value specified for StatBlob")
	}

	var r0 *store.BlobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*store.BlobInfo, error)); ok {
		return returnFunc(repository1, digest1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *store.BlobInfo); ok {
		r0 = returnFunc(repository1, digest1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(repository1, digest1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryService_StatBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatBlob'
type RepositoryService_StatBlob_Call struct {
	*mock.Call
}

// StatBlob is a helper method to define mock.On call
//   - repository1 string
//   - digest1 string
func (_e *RepositoryService_Expecter) StatBlob(repository1 interface{}, digest1 interface{}) *RepositoryService_StatBlob_Call {
	return &RepositoryService_StatBlob_Call{Call: _e.mock.On("StatBlob", repository1, digest1)}
}

func (_c *RepositoryService_StatBlob_Call) Run(run func(repository1 string, digest1 string)) *RepositoryService_StatBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryService_StatBlob_Call) Return(blobInfo *store.BlobInfo, err error) *RepositoryService_StatBlob_Call {
	_c.Call.Return(blobInfo, err)
	return _c
}

func (_c *RepositoryService_StatBlob_Call) RunAndReturn(run func(repository1 string, digest1 string) (*store.BlobInfo, error)) *RepositoryService_StatBlob_Call {
	_c.Call.Return(run)
	return _c
}

// StatManifest provides a mock function for the type RepositoryService
func (_mock *RepositoryService) StatManifest(repository1 string, reference string) (*store.BlobInfo, error) {
	ret := _mock.Called(repository1, reference)

	if len(ret) == 0 {
		panic("no return value specified for StatManifest")
	}

	var r0 *store.BlobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*store.BlobInfo, error)); ok {
		return returnFunc(repository1, reference)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *store.BlobInfo); ok {
		r0 = returnFunc(repository1, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(repository1, reference)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryService_StatManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatManifest'
type RepositoryService_StatManifest_Call struct {
	*mock.Call
}

// StatManifest is a helper method to define mock.On call
//   - repository1 string
//   - reference string
func (_e *RepositoryService_Expecter) StatManifest(repository1 interface{}, reference interface{}) *RepositoryService_StatManifest_Call {
	return &RepositoryService_StatManifest_Call{Call: _e.mock.On("StatManifest", repository1, reference)}
}

func (_c *RepositoryService_StatManifest_Call) Run(run func(repository1 string, reference string)) *RepositoryService_StatManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryService_StatManifest_Call) Return(blobInfo *store.BlobInfo, err error) *RepositoryService_StatManifest_Call {
	_c.Call.Return(blobInfo, err)
	return _c
}

func (_c *RepositoryService_StatManifest_Call) RunAndReturn(run func(repository1 string, reference string) (*store.BlobInfo, error)) *RepositoryService_StatManifest_Call {
	_c.Call.Return(run)
	return _c
}

// StatUpload provides a mock function for the type RepositoryService
func (_mock *RepositoryService) StatUpload(repository1 string, sessionID string) (*store.BlobInfo, error) {
	ret := _mock.Called(repository1, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for StatUpload")
	}

	var r0 *store.BlobInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*store.BlobInfo, error)); ok {
		return returnFunc(repository1, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *store.BlobInfo); ok {
		r0 = returnFunc(repository1, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(repository1, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryService_StatUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatUpload'
type RepositoryService_StatUpload_Call struct {
	*mock.Call
}

// StatUpload is a helper method to define mock.On call
//   - repository1 string
//   - sessionID string
func (_e *RepositoryService_Expecter) StatUpload(repository1 interface{}, sessionID interface{}) *RepositoryService_StatUpload_Call {
	return &RepositoryService_StatUpload_Call{Call: _e.mock.On("StatUpload", repository1, sessionID)}
}

func (_c *RepositoryService_StatUpload_Call) Run(run func(repository1 string, sessionID string)) *RepositoryService_StatUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RepositoryService_StatUpload_Call) Return(blobInfo *store.BlobInfo, err error) *RepositoryService_StatUpload_Call {
	_c.Call.Return(blobInfo, err)
	return _c
}

func (_c *RepositoryService_StatUpload_Call) RunAndReturn(run func(repository1 string, sessionID string) (*store.BlobInfo, error)) *RepositoryService_StatUpload_Call {
	_c.Call.Return(run)
	return _c
}
