// Code generated by mockery. DO NOT EDIT.

package mock

import (
	io "io"

	digest "github.com/opencontainers/go-digest"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/robinkb/cascade-registry/repository"

	store "github.com/robinkb/cascade-registry/store"
)

// RepositoryService is an autogenerated mock type for the RepositoryService type
type RepositoryService struct {
	mock.Mock
}

type RepositoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryService) EXPECT() *RepositoryService_Expecter {
	return &RepositoryService_Expecter{mock: &_m.Mock}
}

// AppendUpload provides a mock function with given fields: _a0, sessionID, r, offset
func (_m *RepositoryService) AppendUpload(_a0 string, sessionID string, r io.Reader, offset int64) error {
	ret := _m.Called(_a0, sessionID, r, offset)

	if len(ret) == 0 {
		panic("no return value specified for AppendUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, io.Reader, int64) error); ok {
		r0 = rf(_a0, sessionID, r, offset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryService_AppendUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendUpload'
type RepositoryService_AppendUpload_Call struct {
	*mock.Call
}

// AppendUpload is a helper method to define mock.On call
//   - _a0 string
//   - sessionID string
//   - r io.Reader
//   - offset int64
func (_e *RepositoryService_Expecter) AppendUpload(_a0 interface{}, sessionID interface{}, r interface{}, offset interface{}) *RepositoryService_AppendUpload_Call {
	return &RepositoryService_AppendUpload_Call{Call: _e.mock.On("AppendUpload", _a0, sessionID, r, offset)}
}

func (_c *RepositoryService_AppendUpload_Call) Run(run func(_a0 string, sessionID string, r io.Reader, offset int64)) *RepositoryService_AppendUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(io.Reader), args[3].(int64))
	})
	return _c
}

func (_c *RepositoryService_AppendUpload_Call) Return(_a0 error) *RepositoryService_AppendUpload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryService_AppendUpload_Call) RunAndReturn(run func(string, string, io.Reader, int64) error) *RepositoryService_AppendUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CloseUpload provides a mock function with given fields: _a0, id, _a2
func (_m *RepositoryService) CloseUpload(_a0 string, id string, _a2 string) error {
	ret := _m.Called(_a0, id, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CloseUpload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(_a0, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryService_CloseUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseUpload'
type RepositoryService_CloseUpload_Call struct {
	*mock.Call
}

// CloseUpload is a helper method to define mock.On call
//   - _a0 string
//   - id string
//   - _a2 string
func (_e *RepositoryService_Expecter) CloseUpload(_a0 interface{}, id interface{}, _a2 interface{}) *RepositoryService_CloseUpload_Call {
	return &RepositoryService_CloseUpload_Call{Call: _e.mock.On("CloseUpload", _a0, id, _a2)}
}

func (_c *RepositoryService_CloseUpload_Call) Run(run func(_a0 string, id string, _a2 string)) *RepositoryService_CloseUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RepositoryService_CloseUpload_Call) Return(_a0 error) *RepositoryService_CloseUpload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryService_CloseUpload_Call) RunAndReturn(run func(string, string, string) error) *RepositoryService_CloseUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBlob provides a mock function with given fields: _a0, _a1
func (_m *RepositoryService) DeleteBlob(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBlob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryService_DeleteBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBlob'
type RepositoryService_DeleteBlob_Call struct {
	*mock.Call
}

// DeleteBlob is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *RepositoryService_Expecter) DeleteBlob(_a0 interface{}, _a1 interface{}) *RepositoryService_DeleteBlob_Call {
	return &RepositoryService_DeleteBlob_Call{Call: _e.mock.On("DeleteBlob", _a0, _a1)}
}

func (_c *RepositoryService_DeleteBlob_Call) Run(run func(_a0 string, _a1 string)) *RepositoryService_DeleteBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RepositoryService_DeleteBlob_Call) Return(_a0 error) *RepositoryService_DeleteBlob_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryService_DeleteBlob_Call) RunAndReturn(run func(string, string) error) *RepositoryService_DeleteBlob_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteManifest provides a mock function with given fields: _a0, reference
func (_m *RepositoryService) DeleteManifest(_a0 string, reference string) error {
	ret := _m.Called(_a0, reference)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManifest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, reference)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryService_DeleteManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManifest'
type RepositoryService_DeleteManifest_Call struct {
	*mock.Call
}

// DeleteManifest is a helper method to define mock.On call
//   - _a0 string
//   - reference string
func (_e *RepositoryService_Expecter) DeleteManifest(_a0 interface{}, reference interface{}) *RepositoryService_DeleteManifest_Call {
	return &RepositoryService_DeleteManifest_Call{Call: _e.mock.On("DeleteManifest", _a0, reference)}
}

func (_c *RepositoryService_DeleteManifest_Call) Run(run func(_a0 string, reference string)) *RepositoryService_DeleteManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RepositoryService_DeleteManifest_Call) Return(_a0 error) *RepositoryService_DeleteManifest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryService_DeleteManifest_Call) RunAndReturn(run func(string, string) error) *RepositoryService_DeleteManifest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function with given fields: _a0, tag
func (_m *RepositoryService) DeleteTag(_a0 string, tag string) error {
	ret := _m.Called(_a0, tag)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, tag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryService_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type RepositoryService_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - _a0 string
//   - tag string
func (_e *RepositoryService_Expecter) DeleteTag(_a0 interface{}, tag interface{}) *RepositoryService_DeleteTag_Call {
	return &RepositoryService_DeleteTag_Call{Call: _e.mock.On("DeleteTag", _a0, tag)}
}

func (_c *RepositoryService_DeleteTag_Call) Run(run func(_a0 string, tag string)) *RepositoryService_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RepositoryService_DeleteTag_Call) Return(_a0 error) *RepositoryService_DeleteTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryService_DeleteTag_Call) RunAndReturn(run func(string, string) error) *RepositoryService_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlob provides a mock function with given fields: _a0, _a1
func (_m *RepositoryService) GetBlob(_a0 string, _a1 string) (io.Reader, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetBlob")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (io.Reader, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) io.Reader); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryService_GetBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlob'
type RepositoryService_GetBlob_Call struct {
	*mock.Call
}

// GetBlob is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *RepositoryService_Expecter) GetBlob(_a0 interface{}, _a1 interface{}) *RepositoryService_GetBlob_Call {
	return &RepositoryService_GetBlob_Call{Call: _e.mock.On("GetBlob", _a0, _a1)}
}

func (_c *RepositoryService_GetBlob_Call) Run(run func(_a0 string, _a1 string)) *RepositoryService_GetBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RepositoryService_GetBlob_Call) Return(_a0 io.Reader, _a1 error) *RepositoryService_GetBlob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryService_GetBlob_Call) RunAndReturn(run func(string, string) (io.Reader, error)) *RepositoryService_GetBlob_Call {
	_c.Call.Return(run)
	return _c
}

// GetManifest provides a mock function with given fields: _a0, reference
func (_m *RepositoryService) GetManifest(_a0 string, reference string) (*store.ManifestMetadata, []byte, error) {
	ret := _m.Called(_a0, reference)

	if len(ret) == 0 {
		panic("no return value specified for GetManifest")
	}

	var r0 *store.ManifestMetadata
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string) (*store.ManifestMetadata, []byte, error)); ok {
		return rf(_a0, reference)
	}
	if rf, ok := ret.Get(0).(func(string, string) *store.ManifestMetadata); ok {
		r0 = rf(_a0, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.ManifestMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) []byte); ok {
		r1 = rf(_a0, reference)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(_a0, reference)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RepositoryService_GetManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManifest'
type RepositoryService_GetManifest_Call struct {
	*mock.Call
}

// GetManifest is a helper method to define mock.On call
//   - _a0 string
//   - reference string
func (_e *RepositoryService_Expecter) GetManifest(_a0 interface{}, reference interface{}) *RepositoryService_GetManifest_Call {
	return &RepositoryService_GetManifest_Call{Call: _e.mock.On("GetManifest", _a0, reference)}
}

func (_c *RepositoryService_GetManifest_Call) Run(run func(_a0 string, reference string)) *RepositoryService_GetManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RepositoryService_GetManifest_Call) Return(_a0 *store.ManifestMetadata, _a1 []byte, _a2 error) *RepositoryService_GetManifest_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *RepositoryService_GetManifest_Call) RunAndReturn(run func(string, string) (*store.ManifestMetadata, []byte, error)) *RepositoryService_GetManifest_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function with given fields: _a0, tag
func (_m *RepositoryService) GetTag(_a0 string, tag string) (string, error) {
	ret := _m.Called(_a0, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(_a0, tag)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(_a0, tag)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryService_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type RepositoryService_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
//   - _a0 string
//   - tag string
func (_e *RepositoryService_Expecter) GetTag(_a0 interface{}, tag interface{}) *RepositoryService_GetTag_Call {
	return &RepositoryService_GetTag_Call{Call: _e.mock.On("GetTag", _a0, tag)}
}

func (_c *RepositoryService_GetTag_Call) Run(run func(_a0 string, tag string)) *RepositoryService_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RepositoryService_GetTag_Call) Return(_a0 string, _a1 error) *RepositoryService_GetTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryService_GetTag_Call) RunAndReturn(run func(string, string) (string, error)) *RepositoryService_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// InitUpload provides a mock function with given fields: _a0
func (_m *RepositoryService) InitUpload(_a0 string) (*store.UploadSession, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for InitUpload")
	}

	var r0 *store.UploadSession
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*store.UploadSession, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *store.UploadSession); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.UploadSession)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryService_InitUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitUpload'
type RepositoryService_InitUpload_Call struct {
	*mock.Call
}

// InitUpload is a helper method to define mock.On call
//   - _a0 string
func (_e *RepositoryService_Expecter) InitUpload(_a0 interface{}) *RepositoryService_InitUpload_Call {
	return &RepositoryService_InitUpload_Call{Call: _e.mock.On("InitUpload", _a0)}
}

func (_c *RepositoryService_InitUpload_Call) Run(run func(_a0 string)) *RepositoryService_InitUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RepositoryService_InitUpload_Call) Return(_a0 *store.UploadSession, _a1 error) *RepositoryService_InitUpload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryService_InitUpload_Call) RunAndReturn(run func(string) (*store.UploadSession, error)) *RepositoryService_InitUpload_Call {
	_c.Call.Return(run)
	return _c
}

// ListReferrers provides a mock function with given fields: _a0, _a1, opts
func (_m *RepositoryService) ListReferrers(_a0 string, _a1 string, opts *repository.ListReferrersOptions) (*repository.Referrers, error) {
	ret := _m.Called(_a0, _a1, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListReferrers")
	}

	var r0 *repository.Referrers
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *repository.ListReferrersOptions) (*repository.Referrers, error)); ok {
		return rf(_a0, _a1, opts)
	}
	if rf, ok := ret.Get(0).(func(string, string, *repository.ListReferrersOptions) *repository.Referrers); ok {
		r0 = rf(_a0, _a1, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.Referrers)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, *repository.ListReferrersOptions) error); ok {
		r1 = rf(_a0, _a1, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryService_ListReferrers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReferrers'
type RepositoryService_ListReferrers_Call struct {
	*mock.Call
}

// ListReferrers is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
//   - opts *repository.ListReferrersOptions
func (_e *RepositoryService_Expecter) ListReferrers(_a0 interface{}, _a1 interface{}, opts interface{}) *RepositoryService_ListReferrers_Call {
	return &RepositoryService_ListReferrers_Call{Call: _e.mock.On("ListReferrers", _a0, _a1, opts)}
}

func (_c *RepositoryService_ListReferrers_Call) Run(run func(_a0 string, _a1 string, opts *repository.ListReferrersOptions)) *RepositoryService_ListReferrers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(*repository.ListReferrersOptions))
	})
	return _c
}

func (_c *RepositoryService_ListReferrers_Call) Return(_a0 *repository.Referrers, _a1 error) *RepositoryService_ListReferrers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryService_ListReferrers_Call) RunAndReturn(run func(string, string, *repository.ListReferrersOptions) (*repository.Referrers, error)) *RepositoryService_ListReferrers_Call {
	_c.Call.Return(run)
	return _c
}

// ListTags provides a mock function with given fields: _a0, count, from
func (_m *RepositoryService) ListTags(_a0 string, count int, from string) ([]string, error) {
	ret := _m.Called(_a0, count, from)

	if len(ret) == 0 {
		panic("no return value specified for ListTags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, string) ([]string, error)); ok {
		return rf(_a0, count, from)
	}
	if rf, ok := ret.Get(0).(func(string, int, string) []string); ok {
		r0 = rf(_a0, count, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, string) error); ok {
		r1 = rf(_a0, count, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryService_ListTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTags'
type RepositoryService_ListTags_Call struct {
	*mock.Call
}

// ListTags is a helper method to define mock.On call
//   - _a0 string
//   - count int
//   - from string
func (_e *RepositoryService_Expecter) ListTags(_a0 interface{}, count interface{}, from interface{}) *RepositoryService_ListTags_Call {
	return &RepositoryService_ListTags_Call{Call: _e.mock.On("ListTags", _a0, count, from)}
}

func (_c *RepositoryService_ListTags_Call) Run(run func(_a0 string, count int, from string)) *RepositoryService_ListTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *RepositoryService_ListTags_Call) Return(_a0 []string, _a1 error) *RepositoryService_ListTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryService_ListTags_Call) RunAndReturn(run func(string, int, string) ([]string, error)) *RepositoryService_ListTags_Call {
	_c.Call.Return(run)
	return _c
}

// PutManifest provides a mock function with given fields: _a0, reference, content
func (_m *RepositoryService) PutManifest(_a0 string, reference string, content []byte) (digest.Digest, error) {
	ret := _m.Called(_a0, reference, content)

	if len(ret) == 0 {
		panic("no return value specified for PutManifest")
	}

	var r0 digest.Digest
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, []byte) (digest.Digest, error)); ok {
		return rf(_a0, reference, content)
	}
	if rf, ok := ret.Get(0).(func(string, string, []byte) digest.Digest); ok {
		r0 = rf(_a0, reference, content)
	} else {
		r0 = ret.Get(0).(digest.Digest)
	}

	if rf, ok := ret.Get(1).(func(string, string, []byte) error); ok {
		r1 = rf(_a0, reference, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryService_PutManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutManifest'
type RepositoryService_PutManifest_Call struct {
	*mock.Call
}

// PutManifest is a helper method to define mock.On call
//   - _a0 string
//   - reference string
//   - content []byte
func (_e *RepositoryService_Expecter) PutManifest(_a0 interface{}, reference interface{}, content interface{}) *RepositoryService_PutManifest_Call {
	return &RepositoryService_PutManifest_Call{Call: _e.mock.On("PutManifest", _a0, reference, content)}
}

func (_c *RepositoryService_PutManifest_Call) Run(run func(_a0 string, reference string, content []byte)) *RepositoryService_PutManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *RepositoryService_PutManifest_Call) Return(_a0 digest.Digest, _a1 error) *RepositoryService_PutManifest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryService_PutManifest_Call) RunAndReturn(run func(string, string, []byte) (digest.Digest, error)) *RepositoryService_PutManifest_Call {
	_c.Call.Return(run)
	return _c
}

// PutTag provides a mock function with given fields: _a0, tag, _a2
func (_m *RepositoryService) PutTag(_a0 string, tag string, _a2 string) error {
	ret := _m.Called(_a0, tag, _a2)

	if len(ret) == 0 {
		panic("no return value specified for PutTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(_a0, tag, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryService_PutTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutTag'
type RepositoryService_PutTag_Call struct {
	*mock.Call
}

// PutTag is a helper method to define mock.On call
//   - _a0 string
//   - tag string
//   - _a2 string
func (_e *RepositoryService_Expecter) PutTag(_a0 interface{}, tag interface{}, _a2 interface{}) *RepositoryService_PutTag_Call {
	return &RepositoryService_PutTag_Call{Call: _e.mock.On("PutTag", _a0, tag, _a2)}
}

func (_c *RepositoryService_PutTag_Call) Run(run func(_a0 string, tag string, _a2 string)) *RepositoryService_PutTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *RepositoryService_PutTag_Call) Return(_a0 error) *RepositoryService_PutTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryService_PutTag_Call) RunAndReturn(run func(string, string, string) error) *RepositoryService_PutTag_Call {
	_c.Call.Return(run)
	return _c
}

// StatBlob provides a mock function with given fields: _a0, _a1
func (_m *RepositoryService) StatBlob(_a0 string, _a1 string) (*store.BlobInfo, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for StatBlob")
	}

	var r0 *store.BlobInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*store.BlobInfo, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *store.BlobInfo); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryService_StatBlob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatBlob'
type RepositoryService_StatBlob_Call struct {
	*mock.Call
}

// StatBlob is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *RepositoryService_Expecter) StatBlob(_a0 interface{}, _a1 interface{}) *RepositoryService_StatBlob_Call {
	return &RepositoryService_StatBlob_Call{Call: _e.mock.On("StatBlob", _a0, _a1)}
}

func (_c *RepositoryService_StatBlob_Call) Run(run func(_a0 string, _a1 string)) *RepositoryService_StatBlob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RepositoryService_StatBlob_Call) Return(_a0 *store.BlobInfo, _a1 error) *RepositoryService_StatBlob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryService_StatBlob_Call) RunAndReturn(run func(string, string) (*store.BlobInfo, error)) *RepositoryService_StatBlob_Call {
	_c.Call.Return(run)
	return _c
}

// StatManifest provides a mock function with given fields: _a0, reference
func (_m *RepositoryService) StatManifest(_a0 string, reference string) (*store.BlobInfo, error) {
	ret := _m.Called(_a0, reference)

	if len(ret) == 0 {
		panic("no return value specified for StatManifest")
	}

	var r0 *store.BlobInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*store.BlobInfo, error)); ok {
		return rf(_a0, reference)
	}
	if rf, ok := ret.Get(0).(func(string, string) *store.BlobInfo); ok {
		r0 = rf(_a0, reference)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryService_StatManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatManifest'
type RepositoryService_StatManifest_Call struct {
	*mock.Call
}

// StatManifest is a helper method to define mock.On call
//   - _a0 string
//   - reference string
func (_e *RepositoryService_Expecter) StatManifest(_a0 interface{}, reference interface{}) *RepositoryService_StatManifest_Call {
	return &RepositoryService_StatManifest_Call{Call: _e.mock.On("StatManifest", _a0, reference)}
}

func (_c *RepositoryService_StatManifest_Call) Run(run func(_a0 string, reference string)) *RepositoryService_StatManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RepositoryService_StatManifest_Call) Return(_a0 *store.BlobInfo, _a1 error) *RepositoryService_StatManifest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryService_StatManifest_Call) RunAndReturn(run func(string, string) (*store.BlobInfo, error)) *RepositoryService_StatManifest_Call {
	_c.Call.Return(run)
	return _c
}

// StatUpload provides a mock function with given fields: _a0, sessionID
func (_m *RepositoryService) StatUpload(_a0 string, sessionID string) (*store.BlobInfo, error) {
	ret := _m.Called(_a0, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for StatUpload")
	}

	var r0 *store.BlobInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*store.BlobInfo, error)); ok {
		return rf(_a0, sessionID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *store.BlobInfo); ok {
		r0 = rf(_a0, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.BlobInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryService_StatUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatUpload'
type RepositoryService_StatUpload_Call struct {
	*mock.Call
}

// StatUpload is a helper method to define mock.On call
//   - _a0 string
//   - sessionID string
func (_e *RepositoryService_Expecter) StatUpload(_a0 interface{}, sessionID interface{}) *RepositoryService_StatUpload_Call {
	return &RepositoryService_StatUpload_Call{Call: _e.mock.On("StatUpload", _a0, sessionID)}
}

func (_c *RepositoryService_StatUpload_Call) Run(run func(_a0 string, sessionID string)) *RepositoryService_StatUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *RepositoryService_StatUpload_Call) Return(_a0 *store.BlobInfo, _a1 error) *RepositoryService_StatUpload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryService_StatUpload_Call) RunAndReturn(run func(string, string) (*store.BlobInfo, error)) *RepositoryService_StatUpload_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryService creates a new instance of RepositoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryService {
	mock := &RepositoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
