// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"io"

	"github.com/robinkb/cascade/cluster"
	mock "github.com/stretchr/testify/mock"
)

// NewRestorer creates a new instance of Restorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Restorer {
	mock := &Restorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Restorer is an autogenerated mock type for the Restorer type
type Restorer struct {
	mock.Mock
}

type Restorer_Expecter struct {
	mock *mock.Mock
}

func (_m *Restorer) EXPECT() *Restorer_Expecter {
	return &Restorer_Expecter{mock: &_m.Mock}
}

// Restore provides a mock function for the type Restorer
func (_mock *Restorer) Restore(r io.Reader, peer cluster.Peer) error {
	ret := _mock.Called(r, peer)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader, cluster.Peer) error); ok {
		r0 = returnFunc(r, peer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Restorer_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type Restorer_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - r io.Reader
//   - peer cluster.Peer
func (_e *Restorer_Expecter) Restore(r interface{}, peer interface{}) *Restorer_Restore_Call {
	return &Restorer_Restore_Call{Call: _e.mock.On("Restore", r, peer)}
}

func (_c *Restorer_Restore_Call) Run(run func(r io.Reader, peer cluster.Peer)) *Restorer_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		var arg1 cluster.Peer
		if args[1] != nil {
			arg1 = args[1].(cluster.Peer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Restorer_Restore_Call) Return(err error) *Restorer_Restore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Restorer_Restore_Call) RunAndReturn(run func(r io.Reader, peer cluster.Peer) error) *Restorer_Restore_Call {
	_c.Call.Return(run)
	return _c
}
