// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewSnapshotter creates a new instance of Snapshotter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSnapshotter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Snapshotter {
	mock := &Snapshotter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Snapshotter is an autogenerated mock type for the Snapshotter type
type Snapshotter struct {
	mock.Mock
}

type Snapshotter_Expecter struct {
	mock *mock.Mock
}

func (_m *Snapshotter) EXPECT() *Snapshotter_Expecter {
	return &Snapshotter_Expecter{mock: &_m.Mock}
}

// Snapshot provides a mock function for the type Snapshotter
func (_mock *Snapshotter) Snapshot(w io.Writer) error {
	ret := _mock.Called(w)

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer) error); ok {
		r0 = returnFunc(w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Snapshotter_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type Snapshotter_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
//   - w io.Writer
func (_e *Snapshotter_Expecter) Snapshot(w interface{}) *Snapshotter_Snapshot_Call {
	return &Snapshotter_Snapshot_Call{Call: _e.mock.On("Snapshot", w)}
}

func (_c *Snapshotter_Snapshot_Call) Run(run func(w io.Writer)) *Snapshotter_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Snapshotter_Snapshot_Call) Return(err error) *Snapshotter_Snapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Snapshotter_Snapshot_Call) RunAndReturn(run func(w io.Writer) error) *Snapshotter_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}
